### ISSUE TITLE
OnlyOffice won't load after newest docker update - TRANSPORT_HANDSHAKE_ERROR?

### ISSUE THREAD

**Issue by FelixBuehler** [ONLYOFFICE/Docker-DocumentServer#576] opened 2023-02-02 10:53 UTC
Hey everyone,

since the last update my watchtower did, my OnlyOffice won't load the interface/gui anymore, it just keeps showing the loading-logo until it fails after like 1-2 minutes. Below is the log.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Onlyoffice in Nextcloud starts opening a new tab with the logo loading, but the interface/gui never opens.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
My watchtower updated to the last recent version, since then this happened.

**What is the expected behavior?**
The gui/interface to properly load so I'm able to edit documents

**Did this work in previous versions of DocumentServer?**
Yes. It's still working with e.g. 7.2.2.56

**DocumentServer Docker tag:**
-latest

**Host Operating System:**
Synology DS918+

```
2023-02-02T10:42:58.562275341Z  2023/02/01 20:09:00 [error] 654#654: *3 connect() failed (111: Unknown error) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "domain.tld"
2023-02-02T10:42:58.562153426Z  2023/02/01 20:09:00 [error] 654#654: *3 connect() failed (111: Unknown error) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /healthcheck HTTP/1.1", upstream: "http://127.0.0.1:8000/healthcheck", host: "domain.tld"
2023-02-02T10:42:58.562099233Z  ==&gt; /var/log/onlyoffice/documentserver/nginx.error.log &lt;==
2023-02-02T10:42:58.562046345Z  
2023-02-02T10:42:58.561982731Z  2 Feb 10:35:50 - server is up INFO
2023-02-02T10:42:58.561906142Z  2 Feb 10:35:50 - [620] reading config file: ./config/config.js
2023-02-02T10:42:58.561864448Z  }
2023-02-02T10:42:58.561786254Z    pctThreshold: [ 90 ]
2023-02-02T10:42:58.561741138Z    sets: {},
2023-02-02T10:42:58.561690415Z    },
2023-02-02T10:42:58.561633577Z      'statsd.metrics_received': 0
2023-02-02T10:42:58.561588402Z      'statsd.packets_received': 0,
2023-02-02T10:42:58.561518351Z      'statsd.bad_lines_seen': 0,
2023-02-02T10:42:58.561336214Z    counter_rates: {
2023-02-02T10:42:58.544224164Z  ==&gt; /var/log/onlyoffice/documentserver/metrics/out.log &lt;==
2023-02-02T10:42:58.544183902Z  
2023-02-02T10:42:58.544112890Z  ==&gt; /var/log/onlyoffice/documentserver/metrics/err.log &lt;==
2023-02-02T10:42:58.544055265Z  
2023-02-02T10:42:58.543982601Z  [2023-02-02T10:42:03.437] [WARN] [localhost] [docId] [userId] nodeJS - { name: 'TRANSPORT_HANDSHAKE_ERROR' }
2023-02-02T10:42:58.543902441Z  [2023-02-02T10:42:03.437] [WARN] [localhost] [docId] [userId] nodeJS - Bad request
2023-02-02T10:42:58.543806779Z  [2023-02-02T10:42:03.436] [WARN] [localhost] [docId] [userId] nodeJS - 3
2023-02-02T10:42:58.543748143Z      _
2023-02-02T10:42:58.543690078Z      _maxListeners: undefined,
2023-02-02T10:42:58.543639163Z      _eventsCount: 8,
2023-02-02T10:42:58.543584993Z      },
2023-02-02T10:42:58.543524807Z        pause: [Function: onSocketPause]
2023-02-02T10:42:58.543462845Z        resume: [Function: onSocketResume],
2023-02-02T10:42:58.543411898Z        drain: [Function: bound socketOnDrain],
2023-02-02T10:42:58.543350526Z  ==&gt; /var/log/onlyoffice/documentserver/docservice/out.log &lt;==
2023-02-02T10:42:58.543297203Z  
2023-02-02T10:42:58.543230694Z  ==&gt; /var/log/onlyoffice/documentserver/docservice/err.log &lt;==
2023-02-02T10:42:58.543185523Z  
2023-02-02T10:42:58.543121288Z  [2023-02-02T10:38:12.424] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2023-02-02T10:42:58.543058628Z  [2023-02-02T10:38:12.415] [WARN] [localhost] [docId] [userId] nodeJS - worker 864 started.
2023-02-02T10:42:58.542990812Z  [2023-02-02T10:38:12.388] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2023-02-02T10:42:58.542938939Z  [2023-02-02T10:35:57.409] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2023-02-02T10:42:58.542874013Z  [2023-02-02T10:35:57.403] [WARN] [localhost] [docId] [userId] nodeJS - worker 673 started.
2023-02-02T10:42:58.542795714Z  [2023-02-02T10:35:57.379] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2023-02-02T10:42:58.542731784Z  [2023-02-01T20:20:25.143] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2023-02-02T10:42:58.542659350Z  [2023-02-01T20:20:25.136] [WARN] [localhost] [docId] [userId] nodeJS - worker 822 started.
2023-02-02T10:42:58.542589242Z  [2023-02-01T20:20:25.113] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2023-02-02T10:42:58.542505248Z  [2023-02-01T20:18:46.579] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
2023-02-02T10:42:58.542430410Z  ==&gt; /var/log/onlyoffice/documentserver/converter/out.log &lt;==
2023-02-02T10:42:58.542353910Z  
2023-02-02T10:42:58.542135555Z  ==&gt; /var/log/onlyoffice/documentserver/converter/err.log &lt;==
2023-02-02T10:42:58.314641546Z  
2023-02-02T10:42:58.306213574Z   * Reloading nginx configuration nginx       [151G [145G[ OK ]
```

**Comment by hmt** [comment] 2023-02-03 11:59
reverted to 7.2 which works ok

**Comment by pawel-szopinski** [comment] 2023-02-03 20:32
Same here. I've spent several hours, but the solution was nowhere to be found. Reverted to 7.2 and everything works fine again.

**Comment by pdemaret** [comment] 2023-02-05 12:52
Same here. Reverted to latest 7.2 which works OK.

**Comment by urnash** [comment] 2023-02-05 18:01
Same here.

**Comment by igwyd** [comment] 2023-02-05 19:44
Guess it the same problem as https://github.com/ONLYOFFICE/DocumentServer/issues/2084 because we switched to socket.io. Make changes to your apache proxy config https://github.com/ONLYOFFICE/document-server-proxy/pull/27.

**Comment by pawel-szopinski** [comment] 2023-02-05 20:07
It does not happen only on apache. I use nginx as my proxy (nginx proxy manager to be precise).

**Comment by igwyd** [comment] 2023-02-05 20:15
@pawel-szopinski i haven't experience with nginx proxy manager, but i cheked our examples nginx configs with 7.3 and are works. https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx

**Comment by pdemaret** [comment] 2023-02-07 18:08
Thank you @igwyd. I am using document-server behind a nginx reverse proxy (https to http), and was experiencing the issue (as stated above). I copied the settings from https://github.com/ONLYOFFICE/document-server-proxy/blob/master/nginx/proxy-https-to-http.conf into my .conf file, and it works now.
I did not have all the proxy_set_header directives, nor were they with the same parameters.
Thanks.

**Comment by pawel-szopinski** [comment] 2023-02-07 19:07
Ok, to everyone who uses Nginx Proxy Manager, just enable "Websockets Support" in your ONLYOFFICE proxy host. It's in the very first tab (Details).

**Comment by lephtHanded** [comment] 2023-02-08 16:02
> Ok, to everyone who uses Nginx Proxy Manager, just enable "Websockets Support" in your ONLYOFFICE proxy host. It's in the very first tab (Details).

THIS!
thanks, was about to chime in the problems and my reversion to 7.2 - just updated and clicked the one button on Ngnix Proxy Manager and everything is working.

**Comment by FelixBuehler** [comment] 2023-02-15 10:14
Seems to be fixed with the newest update for me. Can you confirm?

**Comment by pawel-szopinski** [comment] 2023-02-15 20:16
Yes, confirmed, at least in case one uses Nginx Proxy Manager, enabling Websockets Support is no longer required, so everything's working as it used to in ver. 7.2.

**Comment by derritter88** [comment] 2023-02-15 20:20
Same here - as soon as I upgrade to version 7.3 at my Kubernetes cluster it won't open any office file.
With the latest 7.2 it works properly

**Comment by ant0nwax** [comment] 2023-02-16 17:06
I have made some oberservations but no clue yet.

background:
- onlyoffice runs on https on a centos 8 stream
- httpd proxy runs on another centos 7 host
- nextcloud runs on https on a centos 8 stream, too

1. access from nextcloud does not work anymore because one url does say bad gateway, and maybe others too
https://onlyoffice.REMOVED.COM/healthcheck 
Returns 502 Bad Gateway / nginx
https://github.com/ONLYOFFICE/DocumentServer/issues/2083
recommends nothing useful yet

2. according to docs a script needs to be run after you want to setup https. that script does not work:
/usr/bin/documentserver-update-securelink.sh
it returns error:
json: error: ENOENT: no such file or directory, open '/etc/onlyoffice/documentserver/local.json'
https://github.com/ONLYOFFICE/DocumentServer/issues/2050
recommends reinstalling onlyoffice :)

3. further this error exists in the file /var/log/onlyoffice/documentserver/docservice/out.log
[2023-02-16T17:44:41.788] [ERROR] [localhost] [docId] [userId] nodeJS - DB table "task_result" does not contain tenant column, columns info: [{"column_name":"id"},{"column_name":"status"},{"column_name":"status_info"},{"column_name":"created_at"},{"column_name":"last_open_date"},{"column_name":"user_index"},{"column_name":"change_id"},{"column_name":"callback"},{"column_name":"baseurl"},{"column_name":"password"}]
https://github.com/ONLYOFFICE/DocumentServer/issues/1911

everything works on 7.1 but not on 7.2 and not on 7.3 i tried already 4 upgrades all failed

i guess i really need to roll back to 7.1 which was super stable and will watch all theses threads :)
i am not used to reinstall a software because an update breaks... i might lose my configuration that was done

**Comment by igwyd** [comment] 2023-02-17 08:44
Hello @ant0nwax, you are missing /etc/onlyoffice/documentserver/local.json, our updates need it. Can you run ```/usr/bin/documentserver-configure.sh``` for creating it, move all your changes to local.json from default.json, and try to update again. We not recomend make chanes in default.json.  [I want to change some Document Server parameters from the default.json configuration file. How can I do that so that my changes were not lost after update?](https://api.onlyoffice.com/editors/faq/general )

**Comment by ant0nwax** [comment] 2023-02-17 09:32
@igwyd thank you for the contribution, I am restored the snapshot of 7.1 and did following steps:

- test OnlyOffice 7.1 with Nextcloud - works
- run `usr/bin/documentserver-configure.sh` - was heavy to find out that you need to add guest and no password for rabbitmq
- check if `/etc/onlyoffice/documentserver/local.json` was created - yes was created, great :)
- test onlyoffice 7.1 with nextcloud - FAILED, DOES NOT WORK ANYMORE

i suppose the script destroyed my HTTPS configuration of OnlyOffice
might be located anywhere in between gninx and php-fpm configs
could you help me? only port 80 is listening but 443 is needed.
 
tcp       80      0 0.0.0.0:5672            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8126            0.0.0.0:*               LISTEN

Thank you

**Comment by ant0nwax** [comment] 2023-02-17 11:31
Thank you for pointing again in the right direction, it seems it is a documentation issue that many creators and users do not develop or integrrate https environments, i learned for security reasons to use https even in local networks. i think the attitude worldwide could maybe one day change in order to have this as a default... for chrome and edge these are mandatory things nowadays that get moqued out... not a good test scenario :)

Because i am not using IPV6 on the onlyoffice host, I could share the following change was needed additionally:
I added a # in front of the IPV6 listen addresses
```
[root@onlyoffice ~]# grep  -E '\[' /etc/onlyoffice/documentserver/nginx/ds.conf
#  listen [::]:80 default_server;
#  listen [::1]:80;
#  listen [::]:443 ssl default_server;
```

and then finally when i used point 5 of the docs

[root@onlyoffice ~]# bash /usr/bin/documentserver-update-securelink.sh
ds:docservice: stopped
ds:docservice: ERROR (spawn error)
ds:converter: stopped
ds:converter: ERROR (spawn error)
Redirecting to /bin/systemctl reload nginx.service

now what is that connected to?

I will not yet try to update as this step again produced an error.
nginx is up and running now with https:

```
[root@onlyoffice ~]# netstat -an | grep LISTEN
tcp        0      0 0.0.0.0:5672            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8126            0.0.0.0:*               LISTEN
```
OnlyOffice is back on Port 443 but Nextcloud has the 502 Bad Gateway like in initial issue post
https://github.com/ONLYOFFICE/DocumentServer/issues/2083

![image](https://user-images.githubusercontent.com/33480652/219640573-4f0bbded-c513-46cc-a574-6210ca992abe.png)

**Comment by ant0nwax** [comment] 2023-02-17 11:35
It must be an selinux issue, so how to fix it if i shall not touch the json file :) I would like to avoid setting selinux to permissive

found in /var/log/onlyoffice/documentserver/docservice/err.log
```
Error: Config file /etc/onlyoffice/documentserver/default.json cannot be read
    at Config.<anonymous> (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:752:11)
    at /snapshot/server/build/server/DocService/node_modules/config/lib/config.js:595:28
    at Array.forEach (<anonymous>)
    at /snapshot/server/build/server/DocService/node_modules/config/lib/config.js:591:14
    at Array.forEach (<anonymous>)
    at Config.<anonymous> (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:590:13)
    at new Config (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:136:27)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:1638:31)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
pkg/prelude/bootstrap.js:1697
      throw error;
      ^
```

**Comment by ant0nwax** [comment] 2023-02-17 11:38
step 2 is missing a point:

`sudo cp -f /etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl /etc/onlyoffice/documentserver/nginx/ds.conf`
`chown ds:ds  /etc/onlyoffice/documentserver/nginx/ds.conf`
 please fix the docs :)

**Comment by ant0nwax** [comment] 2023-02-17 13:06
hmm

```
[root@onlyoffice ~]# ls -laZ /etc/onlyoffice/documentserver/
total 56
drwxr-xr-x. 6 root root system_u:object_r:etc_t:s0       284 Feb 17 12:44 .
drwxr-xr-x. 4 root root system_u:object_r:etc_t:s0        58 Feb 19  2022 ..
-r--r-----. 1 root root unconfined_u:object_r:etc_t:s0 13909 Feb 17 12:44 default.json
-r--r-----. 1 ds   ds   system_u:object_r:etc_t:s0     12402 Feb 28  2022 default.json.rpmsave
-r--r-----. 1 ds   ds   system_u:object_r:etc_t:s0      1595 May 30  2022 development-linux.json
-r--r-----. 1 ds   ds   system_u:object_r:etc_t:s0      1735 May 30  2022 development-mac.json
-r--r-----. 1 ds   ds   system_u:object_r:etc_t:s0      1747 May 30  2022 development-windows.json
-rw-r-----. 1 ds   ds   unconfined_u:object_r:etc_t:s0   885 Feb 17 10:26 local.json
drwxr-xr-x. 2 root root system_u:object_r:etc_t:s0        53 Dec 20 17:48 log4js
drwxr-xr-x. 2 root root system_u:object_r:etc_t:s0        21 Dec 20 17:48 logrotate
drwxr-xr-x. 3 root root system_u:object_r:etc_t:s0       103 Feb 17 12:21 nginx
-r--r-----. 1 ds   ds   system_u:object_r:etc_t:s0      2504 May 30  2022 production-linux.json
-r--r-----. 1 ds   ds   system_u:object_r:etc_t:s0      1803 May 30  2022 production-windows.json
drwxr-xr-x. 2 root root system_u:object_r:etc_t:s0        91 Feb 19  2022 supervisor

```

**Comment by ant0nwax** [comment] 2023-02-17 13:15
please see the following as a bug report and hand it over to QA team, it will not work for anyone on centos or redhat if selinux is enabled

```
[root@onlyoffice docservice]# bash /usr/bin/documentserver-update-securelink.sh
ds:docservice: ERROR (not running)
ds:docservice: ERROR (spawn error)
ds:converter: ERROR (not running)
ds:converter: ERROR (spawn error)
```

it destroyed the selinux context and the owner of the file /etc/onlyoffice/documentserver/default.json

**Comment by ant0nwax** [comment] 2023-02-17 13:28
I WOULD LIKE TO POINT OUT I AM STILL ON 7.1 BEFORE ANY UPGRADE I JSUT WAS RUNNING ONE SCRIPT
/usr/bin/documentserver-update-securelink.sh 

this destroyed the whole installation :)

**Comment by ostasevych** [comment] 2023-02-17 20:33
Please, upgrade it in accordance with the upgrades to the upstream version of OnlyOffice, see https://github.com/ONLYOFFICE/DocumentServer/issues/2083

**Comment by ant0nwax** [comment] 2023-02-17 20:54
so i shall ignore the errors and port 8000 does not listen, but i shall upgrade according the other bug report? which is OPEN ;)

whats the reason for the two mentioned scripts breaking a working 7.1 installation?

missing QA in release pipeline 

 i will not trial and error upgrade anymore before some more users are encouraged to break their installations ;)

**Comment by ant0nwax** [comment] 2023-02-19 09:52
i am trying a new upgerade, this is not docker

  Running scriptlet: onlyoffice-documentserver-7.3.2-8.el7.x86_64                                                                                                    153/419
Preparing for shutdown, it can take a lot of time, please wait...Done
Stopping documentserver services...

  Upgrading        : onlyoffice-documentserver-7.3.2-8.el7.x86_64                                                                                                    153/419
warning: /etc/onlyoffice/documentserver/nginx/ds.conf created as /etc/onlyoffice/documentserver/nginx/ds.conf.rpmnew

  Running scriptlet: onlyoffice-documentserver-7.3.2-8.el7.x86_64                                                                                                    153/419

**Comment by ant0nwax** [comment] 2023-02-19 11:36
i found this thread, maybe this is connected:
https://github.com/socketio/socket.io/issues/3768

**Comment by ant0nwax** [comment] 2023-02-19 11:37
I started a new thread for my issue:
https://github.com/ONLYOFFICE/DocumentServer/issues/2115

**Comment by Rita-Bubnova** [comment] 2024-11-20 08:07
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-11-20 08:07 UTC
Labels: fixed
