### ISSUE TITLE
rtl crying in the corner

### ISSUE THREAD

**Issue by firashacker** [ONLYOFFICE/Docker-DocumentServer#427] opened 2022-04-13 23:06 UTC
the fact that rtl lack had been reported 5 year's ago and still the same annoying me i't the reason i can't use the suit

**Comment by ShockwaveNN** [comment] 2022-04-14 07:04
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

Sorry, we got no news about this, I cannot change priorities, it's better to contact sales@onlyoffice.com

**Closed by ShockwaveNN** 2022-04-14 07:04 UTC
