### ISSUE TITLE
Automatically open the slide show page when open with editorConfig.mode:edit,type:desktop

### ISSUE THREAD

**Issue by daolie** [ONLYOFFICE/Docker-DocumentServer#541] opened 2022-11-08 06:03 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When I use editorConfig.mode=edit to open pptx, it will automatically jump to the slide show page. Use the same configuration to open other files, some will, and some will not. Are there any incorrect or missing configurations.
Even the same file in different paths and opened with the same configuration. Some will enter the slide show mode, while others will not
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

https://user-images.githubusercontent.com/24371206/200487350-ef9cbe7b-cbac-4924-98f8-36c6319aa0f5.mp4

**What is the expected behavior?**
Do not open slide show when editing
**Did this work in previous versions of DocumentServer?**
yes
**DocumentServer Docker tag:**
7.2
**Host Operating System:**
windows7

**Comment by ShockwaveNN** [comment] 2022-11-08 07:39
Hi, I need some more details to localize this issue

If this happens only for some random file - are you sure that you properly set uniq key for each file?

If so I need something that I can reproduce on my system, some example code and instruction how to run it

**Comment by ShockwaveNN** [comment] 2022-11-08 08:43
```
      "about": false,

```

I think it can be disabled only in paid license, do you have one? Because I think it's faster to solve this issue via our paid support system

I don't see some specific problem in your example

**Comment by daolie** [comment] 2022-11-09 01:12
> ```
>       "about": false,
> ```
> 
> I think it can be disabled only in paid license, do you have one? Because I think it's faster to solve this issue via our paid support system
> 
> I don't see some specific problem in your example

Sorry i don't have a paid license, it doesn't work.
Can you see the content of the video I uploaded?
Is there any scenario where such a situation occurs? 
I can reproduce on my system with different DocumentServer containers.(DocumentServer Docker tag: 7.2)

**Comment by daolie** [comment] 2022-11-09 08:17
I seem to have found a solution. If the above problem occurs, modify document.title and the file can be opened normally.

**Comment by ShockwaveNN** [comment] 2022-11-09 13:49
> Sorry i don't have a paid license, it doesn't work.

So if you don't have license those keys will do nothing and they actions are undfeinde

So maybe some problem with those permissions which is not aviable in opensource versions
If we want dig out the problem we should simpify this config as much as possible

> 
I seem to have found a solution. If the above problem occurs, modify document.title and the file can be opened normally.

Not sure why this happens

**Comment by daolie** [comment] 2022-11-10 07:23
> > Sorry i don't have a paid license, it doesn't work.
> 
> So if you don't have license those keys will do nothing and they actions are undfeinde
> 
> So maybe some problem with those permissions which is not aviable in opensource versions If we want dig out the problem we should simpify this config as much as possible
> 
> > I seem to have found a solution. If the above problem occurs, modify document.title and the file can be opened normally.
> 
> Not sure why this happens


Maybe it caused by some cache? Anyway, it's ok now, thanks for your reply.

**Comment by ShockwaveNN** [comment] 2022-11-10 07:44
I don't know about any problem with cache by default, but if you've setup some proxy - it can be

But if it solved - I'll close the issue

**Closed by ShockwaveNN** 2022-11-10 07:44 UTC
