### ISSUE TITLE
Recent versions no longer compatible with old script

### ISSUE THREAD

**Issue by iamdoubz** [ONLYOFFICE/Docker-DocumentServer#520] opened 2022-10-24 21:24 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] Bug

**What is the current behavior?**

Cannot connect to Docker container on local port.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I ran the following start script:

```
sudo docker run -i -t -d --restart=always -e JWT_ENABLED=true -e JWT_SECRET=itisntthatsecure -p 9981:80 -p 9982:443 \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
    -v /app/onlyoffice/DocumentServer/rabbitmq:/var/lib/rabbitmq \
    -v /app/onlyoffice/DocumentServer/redis:/var/lib/redis \
    -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql  onlyoffice/documentserver
```

**What is the expected behavior?**

I get a welcome page when I navigate to `http://my.local.ip:9981/welcome/`.

**Did this work in previous versions of DocumentServer?**

Yes. In previous version (Docker tag: 7.1.1.23), I simply ran this script to start and it worked until an unknown time:

```
sudo docker run -i -t -d --restart=always -e JWT_ENABLED=true -e JWT_SECRET=itisntthatsecure -p 127.0.0.1:9981:80 -p 127.0.0.1:9982:443 \
-v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
-v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
-v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver
```

**DocumentServer Docker tag:**

latest

**Host Operating System:**

Ubuntu 20.04

**Docker error log:**

```
iamdoubz@computer:~/Gits/oo$ sudo docker logs 78ce6254d225e1a071cb79b85b1d41d94f0b8f0dbeaa8b9af2db945519fa59b2
/var/www/onlyoffice/documentserver/npm/json[23]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7ff73fe5fd90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7ff73fe5fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[24]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7fea828a2d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fea828a2e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[25]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7fc9d4c6fd90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fc9d4c6fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[26]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7fcce1392d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fcce1392e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[27]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7fba50bd8d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fba50bd8e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[28]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7ffb108d4d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7ffb108d4e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[29]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7fc0d6ce9d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fc0d6ce9e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/app/ds/run-document-server.sh: line 215: -3: substring expression < 0
nc: port number invalid: 
Waiting for connection to the  host on port 
nc: port number invalid: 
Waiting for connection to the  host on port 
```

**Comment by ShockwaveNN** [comment] 2022-10-25 06:08
This is duplicate of https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/503

It have nothing to do with run parameters, please udate your docker service engine

**Closed by ShockwaveNN** 2022-10-25 06:08 UTC

**Comment by iamdoubz** [comment] 2022-10-26 16:10
@ShockwaveNN I am running docker service engine 20.10.6. So, I should upgrade to 20.10.21 and my "old" config should run fine?

**Comment by ShockwaveNN** [comment] 2022-10-26 16:12
Yep, we did nothing to change config, but we updated base image to ubuntu:22.04

And it's seems this version is not compatible with not the latest version of docker engine

**Comment by iamdoubz** [comment] 2022-10-26 16:39
Thank you for the information @ShockwaveNN . Could I have a simple request that you add this new requirement to your README or perhaps add a changelog with these new requirements?

**Comment by ShockwaveNN** [comment] 2022-10-27 06:45
Fair enought, I will add that to README and changelog

**Comment by ShockwaveNN** [comment] 2022-10-27 08:15
[Done](https://github.com/ONLYOFFICE/DocumentServer/pull/1959) and [done](https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/526)
