### ISSUE TITLE
Enviroment variables do not change port

### ISSUE THREAD

**Issue by casKd-dev** [ONLYOFFICE/Docker-DocumentServer#151] opened 2019-03-06 03:05 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The document server tries to use the default port and localhost as connection even though `POSTGRESQL_SERVER_HOST` and `POSTGRESQL_SERVER_PORT` are defined.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Use latest docker image
2. Define the two variables
3. Compose up

**What is the expected behavior?**

The document server would use the ports defined

**Did this work in previous versions of DocumentServer?**

Not tested

**DocumentServer Docker tag:**

onlyoffice/documentserver:5.2.8.24 (latest)

**Host Operating System:**

Ubuntu 16.04 xenial
x86_64 Linux 4.4.0-142-generic

**Comment by ShockwaveNN** [comment] 2019-03-06 07:50
Seem trouble actual only for compose
Tred to use docker run env - and everything fine
```
docker run -it -p 80:80 -e POSTGRESQL_SERVER_HOST=192.168.1.1 -e POSTGRESQL_SERVER_PORT=1234 onlyoffice/documentserver:latest
Waiting for connection to the 192.168.1.1 host on port 1234
```

> Define the two variables

How did you define them? Do you edit docker-compose or somehow else?

**Comment by casKd-dev** [comment] 2019-03-06 12:37
> Seem trouble actual only for compose
> Tred to use docker run env - and everything fine

I actually used also docker run with the variables too, same result. Here is what i've tried:

**docker-compose.yml**
```
version: '2'
services:
  documentserver:
    image: onlyoffice/documentserver:latest
    environment:
      - HTTP_CHECK=GET office.redxen.eu/healthcheck
      - EXTRA_SETTINGS=http-check expect string true
      #- POSTGRESQL_SERVER_HOST=HOST
      #- POSTGRESQL_SERVER_PORT=PORT
      #- POSTGRESQL_SERVER_DB_NAME=onlyoffice
      #- POSTGRESQL_SERVER_USER=onlyoffice
      #- POSTGRESQL_SERVER_PASS=PASSWORD
    stdin_open: true
    restart: always
    ports:
      - 3777:80
    volumes:
       - ./config/local.json:/etc/onlyoffice/documentserver/local.json
```

**docker run**
`docker run -e POSTGRESQL_SERVER_HOST=HOST -e POSTGRESQL_SERVER_PORT=PORT -e POSTGRESQL_SERVER_DB_NAME=onlyoffice -e POSTGRESQL_SERVER_USER=onlyoffice -e POSTGRESQL_SERVER_PASSWORD=PASSWORD -v /root/onlyoffice/config/local.json:/etc/onlyoffice/documentserver/local.json onlyoffice/documentserver:latest`

**Comment by ShockwaveNN** [comment] 2019-03-06 12:59
@casKd-dev try to run your command without mounting `local.json`

**Comment by casKd-dev** [comment] 2019-03-06 14:09
> @casKd-dev try to run your command without mounting `local.json`

Did that, no change. Forgot to add that the host is properly set.
So `POSTGRESQL_SERVER_HOST` is working but `POSTGRESQL_SERVER_PORT` is not. Maybe the variable has been changed?

**Comment by casKd-dev** [comment] 2019-03-06 14:48
For some reason it now uses the correct port.

**Comment by casKd-dev** [comment] 2019-03-13 16:44
Coming back up, it seems to have a extremly weird behaviour, it was not using the correct port indeed. Other than that it uses everything correctly. I get a connection refused as it still tries to use the default port.

Oddly enough, later connections work, they use the local.json which has identical entries for user and such.
This can be seen clearly as it attempts to query some stuff, but wrote nothing, not even a line.
The problem here is the initial connection.



![image](https://user-images.githubusercontent.com/30688640/54297537-65c12800-45b7-11e9-9326-6e6ca9775183.png)

**Comment by casKd-dev** [comment] 2019-04-10 14:46
Okay, after a full re-install the port is still not defined. This needs some testing as i am not really sure where the problem really is.

docker-compose.yml related part:
```
documentserver:
    image: onlyoffice/documentserver
    environment:
      POSTGRESQL_SERVER_HOST: 'xxxxx'
      POSTGRESQL_SERVER_PORT: '31002'
      POSTGRESQL_SERVER_DB_NAME: 'onlyoffice'
      POSTGRESQL_SERVER_USER: 'onlyoffice'
      POSTGRESQL_SERVER_PASS: 'xxxxx'
      REDIS_SERVER_HOST: 'xxxxx'
      REDIS_SERVER_PORT: 'xxxxx'
      JWT_ENABLED: 'true'
      JWT_SECRET: 'xxxxxxxxxxxxx'
    ports:
    - target: 80
      published: xxxxx
      protocol: tcp
      mode: host
    stdin_open: true
```
The log output when starting the container:
```
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
psql: could not connect to server: Connection timed out
 Is the server running on host "xxxxxxx" and accepting
 TCP/IP connections on port 5432?
```

**Comment by ShockwaveNN** [comment] 2019-04-22 15:31
@casKd-dev Hi, I'm still was not able to reproduce your issue, could you provide minimal `docker-compose.yml` file in which your problem is reproduces?

**Comment by ShockwaveNN** [comment] 2019-04-22 15:32
Oops, sorry didn't mean to close it

**Comment by casKd-dev** [comment] 2019-05-01 18:42
```
version: '3.7'
documentserver:
    image: onlyoffice/documentserver:latest
    stdin_open: true
    environment:
      #POSTGRESQL_SERVER_HOST: 'localhost'
      #POSTGRESQL_SERVER_PORT: '5432'
      #POSTGRESQL_SERVER_DB_NAME: 'onlyoffice'
      #POSTGRESQL_SERVER_USER: 'onlyoffice'
      #POSTGRESQL_SERVER_PASS: 'password'
      REDIS_SERVER_HOST: 'localhost'
      REDIS_SERVER_PORT: '6377'
      JWT_ENABLED: 'true'
      JWT_SECRET: 'password111'
    ports:
    - '8080:80'
```

**Comment by ShockwaveNN** [comment] 2019-05-06 09:19
@casKd-dev I don't think this is correct compose file, there is no `service` key. Does this just a part? Is there also postgres service in this compose file?

**Comment by casKd-dev** [comment] 2019-05-06 15:41
> @casKd-dev I don't think this is correct compose file, there is no `service` key. Is this just a part? Is there also postgres service in this compose file?

No, it is just a example i've written that is close to my example

**Comment by ShockwaveNN** [comment] 2019-05-06 15:43
@casKd-dev could you provide a full example? There is postgres server is located? In docker-compose or on real server?

**Comment by casKd-dev** [comment] 2019-05-06 15:54
> @casKd-dev could you provide a full example? There is postgres server is located? In docker-compose or on real server?

It has the same behaviour for both cases, i will provide a full example then:
```yaml
version: '3.7'
services:
  documentserver:
      image: onlyoffice/documentserver:latest
      stdin_open: true
      environment:
        POSTGRESQL_SERVER_HOST: 'localhost'
        POSTGRESQL_SERVER_PORT: '5444'
        POSTGRESQL_SERVER_DB_NAME: 'onlyoffice'
        POSTGRESQL_SERVER_USER: 'root'
        POSTGRESQL_SERVER_PASS: 'ExAmPLEPassword123'
        REDIS_SERVER_HOST: 'postgres'
        REDIS_SERVER_PORT: '6377'
        JWT_ENABLED: 'true'
        JWT_SECRET: 'password111'
      ports:
        - '8080:80'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'ExAmPLEPassword123'
    ports:
      - '6777:5432'

**Comment by ShockwaveNN** [comment] 2019-05-06 16:21
@casKd-dev so DocumentServer trying to connect to postgres on `5444`, but postgres is on 6777 port? Just a typo?
Also I'm not sure about networking between containers.
I think you should start by starting container with DocumentServer, attach to it into `bash` and check from `bash` that postgres server is available from DocumentServer container

**Comment by casKd-dev** [comment] 2019-05-06 16:23
> @casKd-dev so DocumentServer trying to connect to postgres on `5444`, but postgres is on 6777 port? Just a typo?
> Also I'm not sure about networking between containers.
> I think you should start by starting container with DocumentServer, attach to it into `bash` and check from `bash` that postgres server is available from DocumentServer container

The container is accessible, i have tested that, but the DocumentServer doesn't use the environment variable for some reason, maybe the variable was removed in some previous commit so now it doesn't get used anymore?

**Comment by ShockwaveNN** [comment] 2019-05-06 16:30
@casKd-dev ok then, still could you provide correct `docker-compose`? It's clearly different ports in your last one, or I'm can't understand something

**Comment by ShockwaveNN** [comment] 2019-05-06 16:31
Also why `REDIS_SERVER_HOST: 'postgres'` postgres in that part

**Comment by casKd-dev** [comment] 2019-05-06 16:32
My bad, i have overlooked that. Now it should be fine @ShockwaveNN

**Comment by ShockwaveNN** [comment] 2019-05-07 07:38
@casKd-dev but ports are still different
In DocumentServer container postgres port is 6377, in postgres container 6777

**Comment by mamema** [comment] 2019-06-04 15:08
i have the same issue. try to set var to 3306 (mysql - mariadb 10) and the logs asking about "is there a server on 5432 port

**Comment by casKd-dev** [comment] 2019-06-07 17:03
@ShockwaveNN Did you use the Docker Hub version? Did you pull the latest version?

**Comment by ShockwaveNN** [comment] 2019-06-17 08:43
@casKd-dev Hi, could you provide full `docker-compose.yml` for which I'll be able to reproduce your problem?

**Comment by casKd-dev** [comment] 2019-06-17 14:37
> @casKd-dev Hi, could you provide full `docker-compose.yml` for which I'll be able to reproduce your problem?
@ShockwaveNN 
The problem can be reproduce with and without a postgres connection, it doesnt matter whatsoever as the variable is not set. I've updated the example above to be correct.

**Comment by ShockwaveNN** [comment] 2019-06-17 14:44
@casKd-dev which one, it's plenty of examples in this thread and all of them seems not updated, I think if you add example in next message it'll be easier to read :)

**Comment by casKd-dev** [comment] 2019-06-17 14:45
> ```yaml
> version: '3.7'
> services:
>   documentserver:
>       image: onlyoffice/documentserver:latest
>       stdin_open: true
>       environment:
>         POSTGRESQL_SERVER_HOST: 'postgres'
>         POSTGRESQL_SERVER_PORT: '6377'
>         POSTGRESQL_SERVER_DB_NAME: 'onlyoffice'
>         POSTGRESQL_SERVER_USER: 'root'
>         POSTGRESQL_SERVER_PASS: 'ExAmPLEPassword123'
>       ports:
>         - '8080:80'
>   postgres:
>     image: postgres
>     environment:
>       POSTGRES_PASSWORD: 'ExAmPLEPassword123'
>     ports:
>       - '6377:5432' 
> ```

**Comment by ShockwaveNN** [comment] 2019-06-17 15:11
@casKd-dev at least first problem I see at your code - ther is no predefined network in your example, so documentserver container and postgres container do not see each other (see https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/docker-compose.yml#L108)

**Comment by casKd-dev** [comment] 2019-06-18 00:00
> @casKd-dev at least first problem I see at your code - there is no predefined network in your example, so documentserver container and postgres container do not see each other (see https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/docker-compose.yml#L108)

There is no need for postgres at all, if you start the container without postgres but with the port changed you will see it will still attempt to connect to the default port. For testing purposes it makes no change. The case is not something that heavily depends on the dependencies themselves.

**Comment by ShockwaveNN** [comment] 2019-06-19 09:14
@casKd-dev 

>if you start the container without postgres but with the port changed you will see it will still attempt to connect to the default port

How to reproduce it? This comment is still actual with latest version
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/151#issuecomment-470004572

But maybe I'm doing something wrong

**Comment by casKd-dev** [comment] 2019-06-19 11:05
> But maybe I'm doing something wrong

Apparently, not. Seems like a recent commit fixed it as i have tested a minimal case and i cannot reproduce it anymore. I will close this. 
![image](https://user-images.githubusercontent.com/30688640/59760559-e1a3ce00-9292-11e9-9f1a-8562d47053f6.png)

**Closed** 2019-06-19 11:05 UTC

**Comment by ShockwaveNN** [comment] 2019-06-19 11:10
Good to hear :)
