### ISSUE TITLE
Adding a new font breaks the end-users UI with an existing cache

### ISSUE THREAD

**Issue by ludovic-montel** [ONLYOFFICE/Docker-DocumentServer#668] opened 2023-10-11 15:02 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

- I use the docker image `onlyoffice/documentserver-de:7.4.1.1` (which generates URL with `/7.4.1-36/`)
- I copy new fonts I want to provide to my end-users : `docker cp /my-fonts/. documentserver:/usr/share/fonts`
- I run the `documentserver-generate-allfonts.sh ` binary to update the fonts inside the container

I can see that the new font files are generated, but : 
- they **do** have the same name as before (and so the same URL)
- the server uses adds a 1-year-cache on this file with the `expires 365d` in the nginx configuration file

This results in end-user browsers that do not updated cached version of the font javascript file. So my end-users use their browser cache and bugs appear : when selecting the new custom font in the select box, the UI is broken and very strange.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See above.

**What is the expected behavior?**

I would like my end-user to have their cache updated, for instance with a hash or a change in the file url.

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:** 

7.4.1.1

**Host Operating System:**

**Comment by igwyd** [comment] 2023-10-12 05:58
Hello @ludovic-montel, we know that issue, but still havn't news. I will remind the developers about this.
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/329

**Comment by ludovic-montel** [comment] 2023-10-12 08:07
Thank you @igwyd for your quick answer 🙂 

I hope the developers will find a workaround, I see in the issue you linked in your answer that you tried adding a random string to the file name but there is no details about the problems they encountered so I cannot really help you.

Good luck to them 😉

**Comment by Rita-Bubnova** [comment] 2023-10-12 13:08
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-10-12 13:08 UTC
Labels: duplicate
