### ISSUE TITLE
Docker config parameter ONLYOFFICE_MAX_DOWNLOAD_BYTES

### ISSUE THREAD

**Issue by jejbq** [ONLYOFFICE/Docker-DocumentServer#771] opened 2024-09-06 09:37 UTC
**Feature: Create a Docker config parameter ONLYOFFICE_MAX_DOWNLOAD_BYTES**

Can your create a Docker configuration parameter **ONLYOFFICE_MAX_DOWNLOAD_BYTES**?

The aim is to set the maxDownloadBytes value in /etc/onlyoffice/documentserver/default.json before the container (onlyoffice/documentserver) starts by implementing the following in run-document-server.sh

```
sed -i -e "s/104857600/${ONLYOFFICE_MAX_DOWNLOAD_BYTES-1073741824}/" ${CONF_DIR}/default.json
supervisorctl restart
```

_Originally posted by @jejbq in https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/770#issuecomment-2333565461_

**Comment by igwyd** [comment] 2024-09-06 09:50
Duplicate of #770

**Comment by Rita-Bubnova** [comment] 2024-09-09 07:42
> @igwyd Please can you remove the **invalid** label from the ticket #770 ?

Done.

**Closed by Rita-Bubnova** 2024-09-09 07:42 UTC
