### ISSUE TITLE
Image onlyoffice ARM64 shows error and does not go up

### ISSUE THREAD

**Issue by talesam** [ONLYOFFICE/Docker-DocumentServer#474] opened 2022-08-11 23:29 UTC
Now the image is out for ARM64, but it's giving an error when uploading, on x86 it works fine.

I'm running on an Oracle ARM64 server.

### Here is doker-compose.yml:
```
version: '3.9'

services:
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    #restart: always
    volumes:
      - /home/tales/Docker/OnlyOffice/data:/var/www/onlyoffice/Data:rw
      - /home/tales/Docker/OnlyOffice/logs:/var/log/onlyoffice
    expose:
      - 80
      - 443
    networks:
      t4l35-net:

networks:
  t4l35-net:
    name: t4l35-net
```

### And here is the error that appears in the log:
```
exec /app/ds/run-document-server.sh: exec format error
```

**Comment by ShockwaveNN** [comment] 2022-08-12 08:35
> but it's giving an error when uploading,

Could you describe what do you mean by `uploading`? Is it giving this `exec format error` on the docker container start or when you've uploaded some file?

**Comment by talesam** [comment] 2022-08-12 15:28
when I run the container, but I'm going to test a new docker-composer that I configured and report here.

**Comment by talesam** [comment] 2022-08-12 15:39
```
tales@t4l35-orion:~$ docker run -itd -p 8181:80 onlyoffice/documentserver
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
1321f1bfac4ab3566e3c2c3157a5680d9622c511cff1d302335e19cf9cbcbb8c
```

**Comment by ShockwaveNN** [comment] 2022-08-12 15:53
This is interesting, seems that for some reason your docker thinks it's on `linux/arm64/v8` platform, not on usual `arm64` and trying to run amd64 as default

I'll recheck on Amazon arm machine right now, but have no access to Oracle cloud, so not sure that I can do with that

**Comment by ShockwaveNN** [comment] 2022-08-12 16:10
Yep, sorry, seems you're right

As I remember we got some troubles with our specific details with our build process, so our devops decided make separate latest tag for arm builds

So please use
```
docker run -itd -p 80:80 onlyoffice/documentserver:latest-arm64
```

**Comment by talesam** [comment] 2022-08-12 16:52
> This is interesting, seems that for some reason your docker thinks it's on `linux/arm64/v8` platform, not on usual `arm64` and trying to run amd64 as default
> 
> I'll recheck on Amazon arm machine right now, but have no access to Oracle cloud, so not sure that I can do with that

If you want, contact me, it can be by email talesam@gmail.com or telegram @talesam, I have some ARM64 machines at oracle, I can make one available for you to test.

**Comment by ShockwaveNN** [comment] 2022-08-13 05:44
>  I have some ARM64 machines at oracle, I can make one available for you to test.

Yeah, sorry, I don't think we need that since it was my mistake (forgetting about correct tag) and your problem reproduces on Amazon ARM ec2 instances, so no point in Oracle ones

> worked with latest-arm64 tag

Thanks, glad to know, in that case I'll close this issue

**Closed by ShockwaveNN** 2022-08-13 05:44 UTC

**Comment by agolybev** [comment] 2022-08-15 07:58
Hi @talesam, thank you for bug report, we are going to publish supported platform version under one tag since 7.2.
