### ISSUE TITLE
Bug after restart container

### ISSUE THREAD

**Issue by ruslanguns** [ONLYOFFICE/Docker-DocumentServer#118] opened 2018-08-10 20:47 UTC
**Do you want to request a *feature* or report a *bug*?**
Probably a bug with docker

**What is the current behavior?**
Service damaged after restart container

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

$ docker restart <container>

then it does not work

**What is the expected behavior?**

tried to get status of services and got 

`error: <class 'socket.error'>, [Errno 99] Cannot assign requested address: file: /usr/lib/python2.7/socket.py line: 575`

**Did this work in previous versions of DocumentServer?**

**DocumentServer Docker tag:**

**Host Operating System:**

**Comment by ShockwaveNN** [comment] 2018-08-13 07:01
What is `rabbitmq` logs?
Possible duplicate of https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/92#issuecomment-388029406

**Comment by ShockwaveNN** [comment] 2018-10-09 11:58
This issue is being closed due to no response

**Closed by ShockwaveNN** 2018-10-09 11:58 UTC
