### ISSUE TITLE
Redis/5.6.0-changes:  TypeError: Cannot set property 'host' of undefined

### ISSUE THREAD

**Issue by edvinkuric** [ONLYOFFICE/Docker-DocumentServer#271] opened 2020-07-30 14:16 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Newest version (5.6.0) of documentserver generates the following error, when trying to setup/start a clean install.
Here is a log:

```
documentserver_1  | undefined:3
documentserver_1  | this.services.CoAuthoring.redis.host = 'redis'
documentserver_1  |                                      ^
documentserver_1  |
documentserver_1  | TypeError: Cannot set property 'host' of undefined
documentserver_1  |     at Object.eval (eval at main (/snapshot/json/lib/json.js), <anonymous>:3:38)
documentserver_1  |     at parseChunk (/snapshot/json/lib/json.js:0:0)
documentserver_1  |     at /snapshot/json/lib/json.js:0:0
documentserver_1  |     at getInput (/snapshot/json/lib/json.js:0:0)
documentserver_1  |     at main (/snapshot/json/lib/json.js:0:0)
documentserver_1  |     at Object.<anonymous> (/snapshot/json/lib/json.js:0:0)
documentserver_1  |     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
documentserver_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
documentserver_1  |     at Module.load (internal/modules/cjs/loader.js:651:32)
documentserver_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
documentserver_1  | undefined:3
documentserver_1  | this.services.CoAuthoring.redis.port = '6379'
documentserver_1  |                                      ^
documentserver_1  |
documentserver_1  | TypeError: Cannot set property 'port' of undefined
documentserver_1  |     at Object.eval (eval at main (/snapshot/json/lib/json.js), <anonymous>:3:38)
documentserver_1  |     at parseChunk (/snapshot/json/lib/json.js:0:0)
documentserver_1  |     at /snapshot/json/lib/json.js:0:0
documentserver_1  |     at getInput (/snapshot/json/lib/json.js:0:0)
documentserver_1  |     at main (/snapshot/json/lib/json.js:0:0)
documentserver_1  |     at Object.<anonymous> (/snapshot/json/lib/json.js:0:0)
documentserver_1  |     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
documentserver_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
documentserver_1  |     at Module.load (internal/modules/cjs/loader.js:651:32)
documentserver_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
With a running docker-onlyoffice-documentserver, just try to reinstall the newest version (upgrade from 5.5.1 to 5.6.0)

**What is the expected behavior?**
Should work, like before

**Did this work in previous versions of DocumentServer?**
yes - i have a test running which tries to install the documentserver every two weeks to catch these errors.

**DocumentServer Docker tag:**
latest

**Host Operating System:**
Ubuntu 20.04
Docker 19.03.11
Docker-compose 1.25.5

**Comment by ShockwaveNN** [comment] 2020-07-30 15:42
Hi, seems this is some of problem with removal of `redis` from `onlyoffice/documentserver` image
But I cannot reproduce this problem

Could you provide your `docker-compose.yml` file? Maybe there some config from older version?

**Comment by edvinkuric** [comment] 2020-07-31 01:59
Hey, thank you for your fast reply.

I think i have located the source of my problem:
in https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/run-document-server.sh#L241 , there is this function "update_redis_settings".
This function was called, when an external redis-server was specified via .env (i had a seperate redis-container != "localhost").

I could fix my issue by updating the script to not call this function anymore.

Is this function still needed (e.g. for integration-edition)?
Also, what is the purpose of "REDIS_ENABLED" in this case? 
Is Redis used in other distributions of the documentserver? (In which cases should this "REDIS_ENABLED"-variable be true?)

**Comment by ShockwaveNN** [comment] 2020-07-31 07:07
> Is this function still needed (e.g. for integration-edition)?
 Yeah, this methods is needed for `onlyoffice-documentserver-ie` and `onlyoffice-documentserver-de`

We are awared with some troubles with redis config and fixed some issues at https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/270

> (i had a seperate redis-container != "localhost").

Could you specify which edition of DocumentServer are you using? If you using `onlyoffice/documentserver` image of DocumentServer Community Edition - there is no need of redis any more

**Comment by ShockwaveNN** [comment] 2020-08-24 07:02
> How can i verify the functionality of Redis in onlyoffice-documentserver-de?

redis is required part in `documentserver-ie` and `document-server-de` file. To be 100% sure you can open file with several user, make some edits, close it, wait around minute and open again - there should be no data lost, and you can also see logs for any errors

> How is redis used exactly or in which submodules (server/web-apps?) is redis used?

`server` only. We removed redis from `onlyoffice-documentserver` version since it's only support 20 concurrent user, so no need of extra dependency, designed to hold a lot of users. So simpler installation of package installation 

Not sure that you mean by other questions, especially `implementation details`, as I said `redis` is required part of `-ie` and `-de` editions to hold more simultaneous users

**Comment by ShockwaveNN** [comment] 2021-04-27 11:23
This issue was closed due to no response.

**Closed by ShockwaveNN** 2021-04-27 11:23 UTC
