### ISSUE TITLE
Running DocumentServer as NonRoot

### ISSUE THREAD

**Issue by derfl0** [ONLYOFFICE/Docker-DocumentServer#501] opened 2022-09-22 12:31 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Server does not start. Ton of permission denied during startup

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Run container with user other than root (e.g. ds) **Warning!** you need to kill the process from another console, since ^C is ignored.
`docker run --rm --platform=linux/amd64 --user ds onlyoffice/documentserver`

**What is the expected behavior?**
Server should start without root permissions

**Did this work in previous versions of DocumentServer?**
No

**DocumentServer Docker tag:**
latest

**Host Operating System:**
Docker

Hey Onlyoffice Team,

i am trying to setup Onlyoffice on a cluster which does not allow me to run anything as root.

Since I am new to only office, it feels to me like you could run a lot of stuff you're running at startup already at buildtime, eg generating fonts. Also would it be possible to provide a plain Docker image without postgressql, Nginx, etc in it only running the application itself?

**Comment by ShockwaveNN** [comment] 2022-09-22 12:34
I think it's similar issue with 
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/172

Which is currently not implemented

**Comment by ShockwaveNN** [comment] 2022-09-22 13:24
Sorry, it's up to developers and I cannot provide any time frame

If you running Onlyoffice in cluster - you probably have some kind of license - you can contact a support and they may change priorites

**Comment by igwyd** [comment] 2024-06-03 05:44
Hello @derfl0, this is Duplicate of #172

**Closed** 2024-06-03 07:47 UTC
