### ISSUE TITLE
/var/www/onlyoffice/documentserver/web-apps/vendor/socketio/socket.io.min.js.map" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by wangchangkui** [ONLYOFFICE/Docker-DocumentServer#644] opened 2023-07-07 02:21 UTC
I am using version 7.4。but now i find logs have one error .why not find socket.io.min.js.map?

**Comment by igwyd** [comment] 2023-08-25 06:25
Hello @wangchangkui, because socket.io not provide distribution without .map, this message is for debugging and does not affect the operation of the ONLYOFFICE-Docs.  I can confirm, this is bug, issue #61138

**Comment by Rita-Bubnova** [comment] 2023-08-25 07:12
Duplicate of https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/763.

**Closed by Rita-Bubnova** 2023-08-25 07:12 UTC
Labels: duplicate
