### ISSUE TITLE
I get an Internet connection restored warning when editing a document

### ISSUE THREAD

**Issue by Origin82** [ONLYOFFICE/Docker-DocumentServer#363] opened 2021-06-09 01:08 UTC
Hi
I have nextcloud ,mariadb and open office installed as a docker container on portainer its all seems to be installed properly and i can get onlyoffice open in my browser by opening the document that i want inside of nextcloud.
the problem is though when i am editing the document i probably get 1 minute into it and i get a warning box popup as follows.

![open office error](https://user-images.githubusercontent.com/85594064/121276517-27d81900-c912-11eb-8fbd-6452ffc3e7a9.png)

this is my first time using onlyoffice so sorry if this is a feature and i need to change a setting or something to stop this but right now its stopping me from using onlyoffice all together.

**Comment by ShockwaveNN** [comment] 2021-06-09 09:26
I think this literally mean that your connection was lost and after restoration you should reopen document to not lost any data you've entered while you was offline for some reason

**Comment by Origin82** [comment] 2021-06-09 18:33
You would think that but it happens over and over again it pop's up I refresh the page and after another minute it happened again  and then I can't do anything until I refresh the page, I'm not losing internet either unless the container is but I'm not sure how to check that

**Comment by ShockwaveNN** [comment] 2021-06-10 07:30
> I'm not losing internet either unless the container is but I'm not sure how to check that

Open Chrome Developers tools and see if there is any red errors while you loosing connection

Also you should check logs of DocumentServer inside of container - `/var/log/onlyoffice/documentserver` for any errors

**Comment by Origin82** [comment] 2021-06-10 23:19
ok so sorry for the massive dump of info but i get 2 red errors at the time of the warning popup

1.  
<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(34, 34, 34); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 240, 240); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(84, 84, 84); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">sockjs.min.js:2</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;">POST <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; color: rgb(38, 38, 38); text-decoration: underline; cursor: pointer; word-break: break-all;">https://onlyoffice.bexcloud.me/6.3.1-32/doc/1254584238/c/355/hknppapd/xhr_send?t=1623366423481</span> 404</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(34, 34, 34); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 240, 240); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">
&nbsp; | r._start | @ | sockjs.min.js:2
-- | -- | -- | --
&nbsp; | (anonymous) | @ | sockjs.min.js:2
&nbsp; | setTimeout (async) | &nbsp; | &nbsp;
&nbsp; | r | @ | sockjs.min.js:2
&nbsp; | r | @ | sockjs.min.js:3
&nbsp; | (anonymous) | @ | sockjs.min.js:2
&nbsp; | r.sendSchedule | @ | sockjs.min.js:2
&nbsp; | r.send | @ | sockjs.min.js:2
&nbsp; | r.send | @ | sockjs.min.js:2
&nbsp; | ke.RW | @ | sdk-all-min.js:169
&nbsp; | ke.I7b | @ | sdk-all-min.js:163
&nbsp; | vd.I7b | @ | sdk-all-min.js:155
&nbsp; | Ce.pVb | @ | sdk-all-min.js:815
&nbsp; | uf.wf | @ | sdk-all.js:8673
&nbsp; | Rb.vQg | @ | sdk-all-min.js:1092
&nbsp; | (anonymous) | @ | app.js:36
&nbsp; | c | @ | app.js:11
&nbsp; | trigger | @ | app.js:11
&nbsp; | onItemClick | @ | app.js:21
&nbsp; | M | @ | app.js:8
&nbsp; | (anonymous) | @ | app.js:8
&nbsp; | (anonymous) | @ | app.js:8
&nbsp; | dispatch | @ | app.js:10
&nbsp; | b.handle | @ | app.js:10

</span></div>


2.


<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(34, 34, 34); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 240, 240); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(84, 84, 84); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">sockjs.min.js:2</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;">WebSocket connection to '<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(84, 84, 84); text-decoration: underline; cursor: pointer; word-break: break-all;">wss://onlyoffice.bexcloud.me/6.3.1-32/doc/1254584238/c/903/ewhv2vyi/websocket</span>' failed: </span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(34, 34, 34); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 240, 240); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">
&nbsp; | e.exports | @ | sockjs.min.js:2
-- | -- | -- | --
&nbsp; | r | @ | sockjs.min.js:3
&nbsp; | r._connect | @ | sockjs.min.js:2
&nbsp; | r._receiveInfo | @ | sockjs.min.js:2
&nbsp; | n | @ | sockjs.min.js:2
&nbsp; | r.emit | @ | sockjs.min.js:2
&nbsp; | (anonymous) | @ | sockjs.min.js:2
&nbsp; | n | @ | sockjs.min.js:2
&nbsp; | r.emit | @ | sockjs.min.js:2
&nbsp; | (anonymous) | @ | sockjs.min.js:2
&nbsp; | n | @ | sockjs.min.js:2
&nbsp; | r.emit | @ | sockjs.min.js:2
&nbsp; | xhr.onreadystatechange | @ | sockjs.min.js:2

</span></div>


and the only error i could find in the logs was this:

[2021-06-09T12:22:31.666] [WARN] nodeJS - Express server starting...
[2021-06-09T12:22:31.669] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-06-09T12:22:31.706] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.3.1. Build: 32
[2021-06-09T12:23:07.387] [WARN] nodeJS - Express server starting...
[2021-06-09T12:23:07.390] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-06-09T12:23:07.423] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.3.1. Build: 32
[2021-06-10T22:46:48.499] [WARN] nodeJS - error description: docId = 3297070892 errorId = Update Version error
[2021-06-10T22:50:59.840] [WARN] nodeJS - error description: docId = 3248535013 errorId = Update Version error
[2021-06-10T22:58:09.868] [WARN] nodeJS - error description: docId = 3049312020 errorId = Update Version error
[2021-06-10T23:03:40.278] [WARN] nodeJS - error description: docId = 4095813127 errorId = Update Version error
[2021-06-10T23:10:39.176] [WARN] nodeJS - error description: docId = 2113181846 errorId = Update Version error
[2021-06-10T23:13:05.566] [WARN] nodeJS - error description: docId = 1254584238 errorId = Update Version error

**Comment by ShockwaveNN** [comment] 2021-06-11 07:15
Could found any usefull info in Chrome log, a lot of stuff, very hard to read - could you show a screenshot of error?

And `Update Version error` is no good in DocumentServer logs

Maybe this is a duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/1157#issuecomment-782089176 and you should add `allow_local_remote_servers` to Nextcloud config?

**Comment by Origin82** [comment] 2021-06-11 10:24
screenshot of error attached

and 'allow_local_remote_servers' => true, added to config

![websocket error](https://user-images.githubusercontent.com/85594064/121672056-aee3e780-caf2-11eb-9e49-a26fa1ef1365.jpg)

**Comment by Origin82** [comment] 2021-06-11 10:30
and this one also come up sometimes could this be a cloudflare issue?

![Post Error](https://user-images.githubusercontent.com/85594064/121672878-a8a23b00-caf3-11eb-8fc3-b94bc9f5618a.jpg)

**Comment by ShockwaveNN** [comment] 2021-06-11 11:25
> and this one also come up sometimes could this be a cloudflare issue

You've never mention you got cloudfare in your setup, but may be

Seems that someone is blocking WebSocket connection, maybe some kind of default firefall, proxy or something like this

**Comment by Origin82** [comment] 2021-06-17 11:17
Just an update i have noticed that the error only pops up a short time after saving the document i turned auto saving off and now it wont throw the error until i save the file manually however the websocket errors are still constantly there in the developer tools.
i also tried disabling any firewalls on my setup and it didnt help

**Comment by ShockwaveNN** [comment] 2021-06-17 11:21
> until i save the file manually

This is 100% not correct behavior

I do not that to say, try to setup another DocumentServer\Nextcloud combo with minimal non-default options see if it works and if it works - try to change settings to be the same to original combo until error happens

I still think this is some kind firewall error, but not sure how to diagnose it

**Comment by Origin82** [comment] 2021-07-19 02:47
this issues seems to be resolved in the latest nextcloud update

**Comment by ShockwaveNN** [comment] 2021-07-19 10:04
Thanks for your report, in that case I'll close this issue

**Closed by ShockwaveNN** 2021-07-19 10:04 UTC
