### ISSUE TITLE
Document-server fails to run

### ISSUE THREAD

**Issue by alexeyvolkoff** [ONLYOFFICE/Docker-DocumentServer#503] opened 2022-09-25 08:39 UTC
Hi, 
my docker-compose integration fails to run after one of the latest upgrades.
Actually, it runs, but I get 502 error on api request.

docket stats is very strange - container consumes only 600k of memory with 2 pids:
 
`5f93fa2e28e        0.20%               656 KiB / 7.906 GiB     0.01%               1.45 kB / 786 B     521 kB / 615 kB     2`

I checked docker logs for the container 5f93fa2e28e  and it shows like it is trying to connect to some invalid port: 
```
Waiting for connection to the  host on port 
nc: port number invalid: 
Waiting for connection to the  host on port 
nc: port number invalid: 
Waiting for connection to the  host on port 
nc: port number invalid: 
Waiting for connection to the  host on port 
nc: port number invalid: 
Waiting for connection to the  host on port 
nc: port number invalid: 
Waiting for connection to the  host on port 
```
Like some config is broken.

I tried to remove the data volume in hope that it will re-create the default config, but it didn't.

Any idea?

**Comment by alexeyvolkoff** [comment] 2022-09-25 09:09
Yes, the problem exists in the latest (7.3) build.
Version 7.2 works fine

**Comment by ShockwaveNN** [comment] 2022-09-25 15:14
What do you mean by v7.3?

There is no such version even in development

https://hub.docker.com/r/onlyoffice/documentserver-ee/tags/?page=1&ordering=last_updated

**Comment by alexeyvolkoff** [comment] 2022-09-25 15:19
sorry, it is tag 7.2 (or latest)
working tag is 7.1 
`onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:**7.1**
    restart: always
    environment:
       - JWT_ENABLED=false
    ports:
       - 127.0.0.1:8082:80
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
`

**Comment by ShockwaveNN** [comment] 2022-09-25 15:40
Try to change ports line for something simpler, not sure if we ever tested with such notation

**Comment by alexeyvolkoff** [comment] 2022-09-25 16:27
tried the simplest way:
docker run -i -t -d -p 8080:80 onlyoffice/documentserver

**Comment by ShockwaveNN** [comment] 2022-09-25 16:31
Got it, seems this is the same problem that occurred for several users, but we never found out a root case or how to reproduce it

Please make sure you've using latest docker sever and describe your host os

Seems this problem depends of host

**Comment by alexeyvolkoff** [comment] 2022-09-25 16:34
cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
[root@onmydisk onmydisk-integration]# docker -v
Docker version 1.13.1, build 64e9980/1.13.1
Sorry, no option for upgrade

**Comment by ShockwaveNN** [comment] 2022-09-25 16:48
this version of docker is not supported by docker

https://endoflife.date/docker-engine

So ubuntu-22.04 image simply too new for that

upgrade to docker 20.10

**Comment by alexeyvolkoff** [comment] 2022-09-25 16:51
Ok, thanks!

**Comment by rabesocke** [comment] 2022-09-26 07:37
I have the same problem with the tag `7.2`. I also downgraded to `7.1`.

I use the all-in-one docker image with no separate volume. The error log says, that the PostgreSQL cannot start and that's why `localhost:5324` is not accessible.

**Comment by ShockwaveNN** [comment] 2022-09-26 07:47
@rabesocke which docker service version are you using? Old and deprecated?

**Comment by rabesocke** [comment] 2022-09-26 07:51
@ShockwaveNN I use just `docker run` with `5:20.10.18~3-0~debian-buster`

**Comment by ShockwaveNN** [comment] 2022-09-26 08:05
I think this may be another problem, you need to provide exact details how to reproduce it

**Comment by rabesocke** [comment] 2022-09-26 08:22
Just start the latest image with the default `docker run` command as you describe in the Github readme

```
sudo docker run -i -t -d -p 80:80 onlyoffice/documentserver:latest
```

That's running, when I create a completely new container.

I now removed all non-persistent volumes in my existing container and started the latest image. Now it's working.

I think, the problem is the migration to Postgres 14. That's not flawless if you have an existing container since several years.

**Comment by aol-nnov** [comment] 2022-09-26 08:35
I think, I've found the root cause

```
root@c90dd84f29ac:/var/www/onlyoffice/documentserver/npm# ./json 
./json[5681]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [./json]
 2: 0x8e096c  [./json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [./json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [./json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [./json]
 6: 0x8bf19c node::Start(int, char**) [./json]
 7: 0x7f1eb4fb4d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f1eb4fb4e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [./json]
Aborted (core dumped)
```

**Comment by aol-nnov** [comment] 2022-09-26 08:42
@ShockwaveNN it pretty much looks like that binary was built with some newer CPU optimisations (such as SSE4).

Recent gitlab release was struggling with the similar issue https://gitlab.com/gitlab-org/gitlab/-/issues/368656

**Comment by ShockwaveNN** [comment] 2022-09-26 08:47
This may be, since we updated our build infrastructure to Ubuntu 16.04 to use newer and faster cef

**Comment by aol-nnov** [comment] 2022-09-26 08:53
This is a disaster... Any plans to support older CPUs as it was prior to 7.2 release?

As an emergency measure I had to rollback to 7.1

**Comment by igwyd** [comment] 2022-09-26 10:52
hello @rabesocke provide please you cpu model and os version. I understand correctly that it is repeated only with new images? And as i see you have docker 20.10, its true?

Hello @aol-nnov provide please too os version and docker version. I doubt this is due to the processor model, but I need to check.

**Comment by aol-nnov** [comment] 2022-09-26 10:55
@igwyd it's proxmox 6.1 here

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

```
docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by igwyd** [comment] 2022-09-26 10:57
@aol-nnov Docker Engine 19.03.5 not supported, please update to the latest version 20.10 and try again.

**Comment by aol-nnov** [comment] 2022-09-26 11:08
@igwyd could you please guide me to that part of documentation?

How come 7.1 works and 7.2 is "not supported"? Minor version bump and such a breaking change without a notice... What a bummer..

**Comment by rabesocke** [comment] 2022-09-26 11:22
For me the problem was the upgrade to `7.2` because of all the last versions I used before several years. All the upgrades from one image to the other were no problem since version `7.2`. It seems that you did an upgrade of Postgres in the Docker image. Before, there was Postgres 12 and now you use Postgres 14.

When I clean up all the volumes and create a complete new container without any previous volumes/data, the image `7.2` is working. That's now my situation - I have no previous data left.

Maybe I or you can reproduce this, when you set up a new container with `7.1` and upgrade then to `7.2`.

```
Prozessor: AMD Turion(tm) II Neo N54L Dual-Core Processor
Kernel: Linux 5.10.0-18-amd64
Docker: 20.10.18~3-0~debian-buster
```

**Comment by aol-nnov** [comment] 2022-09-26 11:26
`/var/www/onlyoffice/documentserver/npm/json` works fine on that CPU, if it is extracted from container. So, it's not unsupported CPU features issue. It might be something with [limits](https://github.com/nodejs/help/issues/1754)...

**Comment by igwyd** [comment] 2022-09-26 11:47
@aol-nnov docker claims to only support the [latest version](https://docs.docker.com/support/#what-is-not-supported), we follow this in docker distribution. We think problem in change base image ubuntu in docker, we updated it from 20.04 to 22.04.

@rabesocke ok, thanks.

**Comment by igwyd** [comment] 2022-09-26 15:32
@rabesocke i can't reproduce, update from 7.1 to 7.2 works correctly for me, the volumes saves including postgres. 
i run:
```
sudo docker run -i -t -d -p 80:80 --restart=always \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  \
    -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \
    -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql  onlyoffice/documentserver
```
and updated it via our manual [here](https://helpcenter.onlyoffice.com/installation/docs-community-update-docker.aspx).
Could you describe your installation and update process in more detail with your specific commands?

**Comment by rabesocke** [comment] 2022-09-27 06:37
I found the reason, why the direct upgrade to `7.2` was not working for me.

I use Portainer and normally upgrade via the "Replace" button with "Pull latest image" active.
<img width="464" alt="image" src="https://user-images.githubusercontent.com/4104867/192450671-79f05dbc-c757-4e2a-88ba-eb5227c692e2.png">

The problem was, that some environment variables were set, that are used in the start up. Here is one variable called `PG_VERSION` which was set to `12`. Due to the upgrade to Ubuntu 22.04 the Postgres was upgraded to `14`. When I change the environment variable to `14` the container with the image `7.2` starts without problems.

**Comment by igwyd** [comment] 2022-09-27 10:52
@rabesocke ok, thanks for details)

**Comment by qqxadyy** [comment] 2022-09-28 03:26
So the 7.2 version must depends on docker 20+?

**Comment by elpito** [comment] 2022-09-28 05:06
The onlyoffice container does not start:

```
/var/www/onlyoffice/documentserver/npm/json[35]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7f7425190d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f7425190e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/app/ds/run-document-server.sh: line 215: -3: substring expression < 0
nc: port number invalid:
```
Ist this probably related to this issue?

**Comment by elpito** [comment] 2022-09-28 05:14
Forgot to post our environment:
Host Almalinux 8.6
Docker:
docker-ce-cli-20.10.6-3.el8.x86_64
docker-ce-20.10.6-3.el8.x86_64
OnlyOffice version 7.2 (latest)

**Comment by aol-nnov** [comment] 2022-09-28 10:42
@elpito `/var/www/onlyoffice/documentserver/npm/json` aborts due some limits (as in `ulimit -a`).

I've extracted it from container [recently](https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/503#issuecomment-1257885948) and run successfully on the same CPU.

@igwyd look! @elpito has docker 20.10 and yet the same error as me! So, it's not the docker version. We need to investigate more...

**Comment by aol-nnov** [comment] 2022-09-28 10:53
Found it!!! https://askubuntu.com/a/1410408

If I start onlyoffice container with `--security-opt seccomp=unconfined`, then aforementioned `json` program does not abort!

It runs fine even on docker 18.09.1. Sooo, @igwyd it has to do with the base image you're now using for your image!

**Comment by elpito** [comment] 2022-09-29 04:04
@aol-nnov OK, thank you. I have checked this before I have posted my comments. But, I have checked it again, but, no luck

**Comment by igwyd** [comment] 2022-09-30 17:08
@aol-nnov @elpito latest version docker include minor of course - 20.10.18 https://endoflife.date/docker-engine

**Comment by ShockwaveNN** [comment] 2022-10-09 17:18
Closing this issue, since 99% sure OP's problem with **VERY** old docker version - 1.13.1

Anyone having similar problems - should upgrade the docker engine to the latest stable version (v20.10.18 as of now)

**Closed by ShockwaveNN** 2022-10-09 17:18 UTC
Labels: waiting feedback

**Comment by ShockwaveNN** [comment] 2022-10-27 08:16
I've added mention of this problem to [CHANGELOG](https://github.com/ONLYOFFICE/DocumentServer/pull/1959) and Docker-DocumentServer's [README](https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/526)

**Comment by WWWWYYYY** [comment] 2022-12-07 09:01
> Hi, my docker-compose integration fails to run after one of the latest upgrades. Actually, it runs, but I get 502 error on api request.
> 
> docket stats is very strange - container consumes only 600k of memory with 2 pids:
> 
> `5f93fa2e28e 0.20% 656 KiB / 7.906 GiB 0.01% 1.45 kB / 786 B 521 kB / 615 kB 2`
> 
> I checked docker logs for the container 5f93fa2e28e and it shows like it is trying to connect to some invalid port:
> 
> ```
> Waiting for connection to the  host on port 
> nc: port number invalid: 
> Waiting for connection to the  host on port 
> nc: port number invalid: 
> Waiting for connection to the  host on port 
> nc: port number invalid: 
> Waiting for connection to the  host on port 
> nc: port number invalid: 
> Waiting for connection to the  host on port 
> nc: port number invalid: 
> Waiting for connection to the  host on port 
> ```
> 
> Like some config is broken.
> 
> I tried to remove the data volume in hope that it will re-create the default config, but it didn't.
> 
> Any idea?

exec   docker run -itd --restart=always --name=onlyoffice **--privileged** -p 8085:80 onlyoffice/documentserver 
it is work.

**Comment by alexeyvolkoff** [comment] 2022-12-13 08:02
Confirming. After upgrading docker to latest **docker-ce** everithing works!

**Comment by liudonghua123** [comment] 2024-06-01 10:05
I have the same issue with docker 26.1.2.

<details><summary>Details</summary>

```
[root@ha-master-1 nextcloud]# cat compose.yml 
version: '3'

services:
  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin@ynu
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.app.ynu.edu.cn
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - LANG=zh_CN.UTF-8
    depends_on:
      - db

  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password

  onlyoffice:
    image: onlyoffice/documentserver
    restart: unless-stopped
    privileged: true
    volumes:
      - ./onlyoffice:/var
    ports:
      - "80"
[root@ha-master-1 nextcloud]# docker compose down onlyoffice
WARN[0000] /root/app/nextcloud/compose.yml: `version` is obsolete 
[+] Running 2/1
 ✔ Container nextcloud-onlyoffice-1  Removed                                                                                                                                        10.6s 
 ! Network nextcloud_default         Resource is still in use                                                                                                                        0.0s 
[root@ha-master-1 nextcloud]# docker compose up -d onlyoffice
WARN[0000] /root/app/nextcloud/compose.yml: `version` is obsolete 
[+] Running 1/1
 ✔ Container nextcloud-onlyoffice-1  Started                                                                                                                                         5.4s 
[root@ha-master-1 nextcloud]# docker compose logs onlyoffice
WARN[0000] /root/app/nextcloud/compose.yml: `version` is obsolete 
onlyoffice-1  | stat: cannot statx '/var/www/onlyoffice/documentserver/server/DocService/docservice': No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 148: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 149: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 158: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 165: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 166: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 167: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 169: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 221: -3: substring expression < 0
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
[root@ha-master-1 nextcloud]# ll onlyoffice/
total 20
drwxr-xr-x. 5 root root 4096 Jun  1 13:56 .
drwxr-xr-x. 5 root root 4096 Jun  1 17:58 ..
drwxr-xr-x. 6 root root 4096 Jun  1 13:56 lib
drwxr-xr-x. 3 root root 4096 Jun  1 13:56 log
drwxr-xr-x. 3 root root 4096 Jun  1 13:56 www
[root@ha-master-1 nextcloud]# rm -rf onlyoffice/
[root@ha-master-1 nextcloud]# docker compose down onlyoffice
WARN[0000] /root/app/nextcloud/compose.yml: `version` is obsolete 
[+] Running 2/2
 ✔ Container nextcloud-onlyoffice-1  Removed                                                                                                                                        10.5s 
 ! Network nextcloud_default         Resource is still in use                                                                                                                        0.0s 
[root@ha-master-1 nextcloud]# docker compose up -d onlyoffice
WARN[0000] /root/app/nextcloud/compose.yml: `version` is obsolete 
[+] Running 1/1
 ✔ Container nextcloud-onlyoffice-1  Started                                                                                                                                         4.6s 
[root@ha-master-1 nextcloud]# docker compose logs onlyoffice
WARN[0000] /root/app/nextcloud/compose.yml: `version` is obsolete 
onlyoffice-1  | stat: cannot statx '/var/www/onlyoffice/documentserver/server/DocService/docservice': No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 148: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 149: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 158: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 165: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 166: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 167: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 169: /var/www/onlyoffice/documentserver/npm/json: No such file or directory
onlyoffice-1  | /app/ds/run-document-server.sh: line 221: -3: substring expression < 0
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
onlyoffice-1  | nc: port number invalid: 
onlyoffice-1  | Waiting for connection to the  host on port 
[root@ha-master-1 nextcloud]# docker compose exec onlyoffice bash
WARN[0000] /root/app/nextcloud/compose.yml: `version` is obsolete 
root@bb9422020a74:/# ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 10:00 ?        00:00:00 /bin/bash /app/ds/run-document-server.sh
root         373       0  0 10:02 pts/0    00:00:00 bash
root         386       1  0 10:02 ?        00:00:00 sleep 1
root         387     373  0 10:02 pts/0    00:00:00 ps -ef
root@bb9422020a74:/# netstat -nap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:39281        0.0.0.0:*               LISTEN      -                   
udp        0      0 127.0.0.11:40381        0.0.0.0:*                           -                   
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
root@bb9422020a74:/# exit
exit
[root@ha-master-1 nextcloud]# 
[root@ha-master-1 nextcloud]# docker --version
Docker version 26.1.2, build 211e74b
[root@ha-master-1 nextcloud]# 
[root@ha-master-1 nextcloud]# docker compose ps
WARN[0000] /root/app/nextcloud/compose.yml: `version` is obsolete 
NAME                     IMAGE                       COMMAND                  SERVICE      CREATED         STATUS         PORTS
nextcloud-app-1          nextcloud                   "/entrypoint.sh apac…"   app          4 hours ago     Up 4 hours     0.0.0.0:8082->80/tcp, :::8082->80/tcp
nextcloud-db-1           mariadb                     "docker-entrypoint.s…"   db           4 hours ago     Up 4 hours     3306/tcp
nextcloud-onlyoffice-1   onlyoffice/documentserver   "/app/ds/run-documen…"   onlyoffice   3 minutes ago   Up 3 minutes   443/tcp, 0.0.0.0:32774->80/tcp, :::32774->80/tcp
[root@ha-master-1 nextcloud]# 
```
</details>

**Comment by liudonghua123** [comment] 2024-06-01 10:10
I have also tried `docker run -itd  --name=onlyoffice --privileged -p 8085:80 onlyoffice/documentserver`. But it seems the `80` port was not served.

```shell
[root@ha-master-1 nextcloud]# docker run -itd  --name=onlyoffice --privileged -p 8085:80 onlyoffice/documentserver
afff68da312633f273a58c07654f7ad1dc32b304005ff82bc67e00402ada57fe
[root@ha-master-1 nextcloud]# docker ps | grep onlyoffice
afff68da3126   onlyoffice/documentserver          "/app/ds/run-documen…"    18 seconds ago   Up 13 seconds                   443/tcp, 0.0.0.0:8085->80/tcp, :::8085->80/tcp                                                                                                                                                                          onlyoffice
bb9422020a74   onlyoffice/documentserver          "/app/ds/run-documen…"    6 minutes ago    Up 6 minutes                    443/tcp, 0.0.0.0:32774->80/tcp, :::32774->80/tcp                                                                                                                                                                        nextcloud-onlyoffice-1
[root@ha-master-1 nextcloud]#
[root@ha-master-1 nextcloud]# docker exec -it onlyoffice bash
root@afff68da3126:/# ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 10:06 pts/0    00:00:00 /bin/bash /app/ds/run-document-server.sh
postgres     310       1  0 10:06 ?        00:00:00 /usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main -c config_file=/etc/postgresql/14/main/postgresql.conf
postgres     312     310  0 10:06 ?        00:00:00 postgres: 14/main: checkpointer 
postgres     313     310  0 10:06 ?        00:00:00 postgres: 14/main: background writer 
postgres     314     310  0 10:06 ?        00:00:00 postgres: 14/main: walwriter 
postgres     315     310  0 10:06 ?        00:00:00 postgres: 14/main: autovacuum launcher 
postgres     316     310  0 10:06 ?        00:00:00 postgres: 14/main: stats collector 
postgres     317     310  0 10:06 ?        00:00:00 postgres: 14/main: logical replication launcher 
root         329       1  0 10:06 pts/0    00:00:00 /bin/sh /etc/init.d/rabbitmq-server start
rabbitmq     419       1  0 10:06 ?        00:00:00 /usr/lib/erlang/erts-12.2.1/bin/epmd -daemon
rabbitmq     479       1 98 10:06 ?        00:00:31 start-stop-daemon --quiet --chuid rabbitmq --start --exec /usr/sbin/rabbitmq-server --pidfile  --background
root         480     329  0 10:06 pts/0    00:00:00 /bin/sh /usr/sbin/rabbitmqctl wait --timeout 600 /var/run/rabbitmq/pid
root         491     480  0 10:06 pts/0    00:00:00 su rabbitmq -s /bin/sh -c /usr/lib/rabbitmq/bin/rabbitmqctl  "wait" "--timeout" "600" "/var/run/rabbitmq/pid"
rabbitmq     492     491  0 10:06 ?        00:00:00 sh -c /usr/lib/rabbitmq/bin/rabbitmqctl  "wait" "--timeout" "600" "/var/run/rabbitmq/pid"
rabbitmq     493     492  2 10:06 ?        00:00:00 /usr/lib/erlang/erts-12.2.1/bin/beam.smp -B -- -root /usr/lib/erlang -progname erl -- -home /var/lib/rabbitmq -- -boot start_clean -no
rabbitmq     503     493  0 10:06 ?        00:00:00 erl_child_setup 1024
root         557       0  0 10:06 pts/1    00:00:00 bash
root         565     557  0 10:06 pts/1    00:00:00 ps -ef
root@afff68da3126:/# netstat -nap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      310/postgres        
tcp        0      0 0.0.0.0:35672           0.0.0.0:*               LISTEN      493/beam.smp        
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      419/epmd            
tcp        0      0 127.0.0.1:46278         127.0.0.1:4369          ESTABLISHED 493/beam.smp        
tcp        0      0 172.17.0.2:4369         172.17.0.2:51868        TIME_WAIT   -                   
tcp        0      0 172.17.0.2:4369         172.17.0.2:51880        TIME_WAIT   -                   
tcp        0      0 127.0.0.1:4369          127.0.0.1:46278         ESTABLISHED 419/epmd            
tcp        0      0 172.17.0.2:4369         172.17.0.2:51854        TIME_WAIT   -                   
tcp        0      0 127.0.0.1:46264         127.0.0.1:4369          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:46262         127.0.0.1:4369          TIME_WAIT   -                   
tcp6       0      0 ::1:5432                :::*                    LISTEN      310/postgres        
tcp6       0      0 :::4369                 :::*                    LISTEN      419/epmd            
udp6       0      0 ::1:53412               ::1:53412               ESTABLISHED 310/postgres        
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     47919698 310/postgres         /var/run/postgresql/.s.PGSQL.5432
unix  3      [ ]         STREAM     CONNECTED     47919038 493/beam.smp         
unix  3      [ ]         STREAM     CONNECTED     47919039 503/erl_child_setup  
root@afff68da3126:/# curl localhost
curl: (7) Failed to connect to localhost port 80 after 0 ms: Connection refused
root@afff68da3126:/# exit
exit
[root@ha-master-1 nextcloud]# docker logs onlyoffice 
 * Starting PostgreSQL 14 database server                                                                                                                                          [ OK ] 
[root@ha-master-1 nextcloud]#
```

**Comment by liudonghua123** [comment] 2024-06-01 10:34
I tried to remove the volumes and it works now for me. Why❓ 

```yml
    volumes:
      - ./onlyoffice:/var
```
