### ISSUE TITLE
 * Starting RabbitMQ Messaging Server rabbitmq-server,  * FAILED - check /var/log/rabbitmq/startup_\{log, _err\},    ...fail!,

### ISSUE THREAD

**Issue by herohamp** [ONLYOFFICE/Docker-DocumentServer#111] opened 2018-06-20 23:15 UTC
* Starting PostgreSQL 9.5 database server,
   ...done.,
 * Starting RabbitMQ Messaging Server rabbitmq-server,
   ...done.,
Starting redis-server: redis-server.,
Starting supervisor: supervisord.,
 * Starting nginx nginx,
   ...done.,
Generating AllFonts.js, please wait...Done,
onlyoffice-documentserver:docservice: stopped,
onlyoffice-documentserver:docservice: started,
onlyoffice-documentserver:converter: stopped,
onlyoffice-documentserver:converter: started,
 * Reloading nginx configuration nginx,
   ...done.,
 * Starting PostgreSQL 9.5 database server,
   ...done.,
 * Starting RabbitMQ Messaging Server rabbitmq-server,
 * FAILED - check /var/log/rabbitmq/startup_\{log, _err\},
   ...fail!,
Starting redis-server: redis-server.,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,
Waiting for connection to the localhost host on port 5672,

**Comment by ShockwaveNN** [comment] 2018-06-21 07:36
sooo, what's inside logs at `/var/log/rabbitmq/startup_{log, _err}`?

**Comment by ShockwaveNN** [comment] 2018-06-21 13:33
Duplicate of https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/92
Try to restart container once more

**Comment by waja** [comment] 2018-06-21 13:45
Indeed https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/92#issuecomment-381528225 fixed it at least for me.

**Comment by ShockwaveNN** [comment] 2018-06-21 14:02
@waja Ok, good to hear. Leave this bug open for a while since you're not reported of issue, maybe @herohamp have some other problem

**Comment by waja** [comment] 2018-06-21 15:14
> @waja Ok, good to hear. Leave this bug open for a while since you're not reported of issue, maybe @herohamp have some other problem

I would suggest to include this ‚workaround‘ into the Docker Readme to prevent generation of too much issues here.

**Comment by ShockwaveNN** [comment] 2018-06-21 15:20
@herohamp I don't know. I don't think a lot of people read readme file in details, but #92 is first place in google search for `‘/var/run/rabbitmq’: Permission denied` query so if it really be a lot of duplicates (for now it is not) and we unable to fix it - we definitely add this info to readme.

**Comment by ShockwaveNN** [comment] 2018-10-09 12:01
Closing since duplicate of #92

**Closed by ShockwaveNN** 2018-10-09 12:01 UTC
