### ISSUE TITLE
Build in Postgres removed in 5.2?

### ISSUE THREAD

**Issue by poVoq** [ONLYOFFICE/Docker-DocumentServer#128] opened 2018-10-01 15:59 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After updating/recreating the docker image of a working document server to the latest version 5.2 it fails to function with the following error in the log file

> Waiting for connection to the 5432 host on port 
> invalid port 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Update docker image from 5.1 to 5.2

**What is the expected behavior?**
Either the documentation should be updated which ENV parameter is needed to connect an external postgres docker image, or the perviously included one needs to work as before?

**Did this work in previous versions of DocumentServer?**
Yes

**DocumentServer Docker tag:**
5.2.0.195 / latest
**Host Operating System:**
Ubuntu16.04

**Comment by ShockwaveNN** [comment] 2018-10-02 06:55
@poVoq no, we do not remove postgres, could you show full `docker run` command to investigate your problem

**Comment by poVoq** [comment] 2018-10-02 14:42
I am running it through Portainer, so I don't really know the docker `run command`.
I just now tried going back to 5.1.5.59 and it works, but now (was not the case before) seems to restart itself every 30 seconds or so.

**Comment by ShockwaveNN** [comment] 2018-10-02 14:49
@poVoq We do not perform any major changes in postgres methods so you should investigate your porter installation.
Main change some Docker stuf to work without interactive flag
https://github.com/ONLYOFFICE/Docker-DocumentServer/pull/99
but I'm not sure how it can be related with Portainer

**Comment by poVoq** [comment] 2018-10-02 14:50
Ok seems like after removing all the old volumes and starting from scratch it is working, I still run it with interactive flag though. I guess something goes wrong with the update process?

**Comment by ShockwaveNN** [comment] 2018-10-02 14:54
@poVoq can you describe which volumes you're left while updating from 5.1 to 5.2, I try to check it

**Comment by poVoq** [comment] 2018-10-02 15:02
I have linked as named volumes:
/var/lib/onlyoffice
/var/lib/postgresql
/var/log/onlyoffice
/var/www/onlyoffice/Data
/etc/onlyoffice
/usr/share/fonts/truetype/custom

Initially I just tried removing the /var/lib/postgresql one, but that didn't make a difference. Afterwards I replaced all and it worked.

Note however that I had this Docker image working for a while now with various 5.1 versions that were released since 1 year I guess, and I always upgraded the image without touching the volumes without issues.

**Comment by ShockwaveNN** [comment] 2018-10-02 15:07
@poVoq oh, I think `/etc/onlyoffice` is the problem, we go a troubles with updating with config between version (previously you update withing 5.1 and bugfixes, it's fine, but we got troubles in 5.1 -> 5.2
I take a look at this

**Comment by ShockwaveNN** [comment] 2018-10-02 15:18
@poVoq ok. can I ask you there did you found information that `/etc/onlyoffice` should be mounted as volume?
I think me may have this in readme in past, but current https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/README.md where I cannot find info about `/etc/onlyoffice`

**Comment by poVoq** [comment] 2018-10-02 15:37
I think it was automatically created as a non-named volume and as I absolutely hate those polluting my volume storage I replaced it :) So yeah, in that case maybe my own fault...

**Comment by ShockwaveNN** [comment] 2018-10-02 15:48
@poVoq we got same problem while testing openshift and fixed it, but do not released it though
https://github.com/ONLYOFFICE/Docker-DocumentServer/commit/f03a23cccd3d96036f66f9b3411720c9286d6a56
I think we can release release this fix in future

**Comment by ShockwaveNN** [comment] 2018-10-03 06:55
@poVoq this fix will be released as 5.2.1
https://github.com/ONLYOFFICE/Docker-DocumentServer/commit/23d320dc2a705dfb4450455a0c24f9f8841104b6

I'm not sure this is exactly a fix of your problem, but since we got no more info - I close issue, feel free to comment if you find some more info how to reproduce your problem

**Closed by ShockwaveNN** 2018-10-03 06:55 UTC

**Comment by MnrGreg** [comment] 2019-06-17 16:25
@ShockwaveNN I see there have been some issues and fixes relating to minishift and OpenShift. Do you or anyone else have deployment manifests for Kubernetes?

**Comment by ShockwaveNN** [comment] 2019-06-18 06:58
@MnrGreg it was for some of our clients, but personally we never tried Kubernetes\OpenShift\Minishift fully working setup
