### ISSUE TITLE
Configure license through env var and/or docker secrets

### ISSUE THREAD

**Issue by ntoljic** [ONLYOFFICE/Docker-DocumentServer#282] opened 2020-08-17 06:50 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The license information for the integration edition must be supplied as a file in the container, either through a mount or through baking the file into a custom image.

**What is the expected behavior?**
What I would like to see is the addition of two environmental variables.
If the env var `LICENSE` is set, the application should read the license information from it directly.
If the env var `LICENSE_FILE` is set, the application should read the license information from the path stored in this variable.

**Did this work in previous versions of DocumentServer?**
No, this is a feature request which would bring the DocumentServer image more in line with docker best practices.

**DocumentServer Docker tag:**
N/A

**Host Operating System:**
N/A

**Comment by ShockwaveNN** [comment] 2020-08-17 07:31
Storing license data in `LICENSE` var I think it's a good idea and we may discuss it with our team, @agolybev any thoughts?

But not sure about `LICENSE_FILE` - we already have an option in `/etc/onlyoffice/documentserver/default.json` - `license:license_file`, not 100% if it works correctly

In general I like this idea

**Comment by igwyd** [comment] 2023-12-15 06:18
Duplicate of https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/326

**Comment by Rita-Bubnova** [comment] 2023-12-15 09:18
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2023-12-15 09:18 UTC
Labels: duplicate
