### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by gaoliuzhu** [ONLYOFFICE/Docker-DocumentServer#521] opened 2022-10-25 06:26 UTC
A service error is reported using a simple container startup instruction
The command is as follows：
docker run -it -d -p 8080:80 --name=onlyoffice onlyoffice/documentserver

log info：
 docker logs -f onlyoffice
/var/www/onlyoffice/documentserver/npm/json[24]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7fc49627dd90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fc49627de40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[25]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7f64ddde5d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f64ddde5e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[26]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7f9b5b0fbd90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f9b5b0fbe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[27]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7f72e2c25d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f72e2c25e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[28]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7fa624dc9d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fa624dc9e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[29]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7f8d5f139d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f8d5f139e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/var/www/onlyoffice/documentserver/npm/json[30]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x8e08f0 node::Abort() [/var/www/onlyoffice/documentserver/npm/json]
 2: 0x8e096c  [/var/www/onlyoffice/documentserver/npm/json]
 3: 0x94c4f7 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/var/www/onlyoffice/documentserver/npm/json]
 4: 0x94c607 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/var/www/onlyoffice/documentserver/npm/json]
 5: 0x8bee61 node::InitializeOncePerProcess(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 6: 0x8bf19c node::Start(int, char**) [/var/www/onlyoffice/documentserver/npm/json]
 7: 0x7fa95e277d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fa95e277e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x842a71  [/var/www/onlyoffice/documentserver/npm/json]
/app/ds/run-document-server.sh: line 215: -3: substring expression < 0
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:
Waiting for connection to the  host on port
nc: port number invalid:

**Comment by ShockwaveNN** [comment] 2022-10-25 06:29
This is a duplicate of https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/503

Please update your docker engine

**Closed by ShockwaveNN** 2022-10-25 06:29 UTC

**Comment by shgninc** [comment] 2023-02-15 10:10
start container with privileged: true

`docker run -it -d --privileged -p 8080:80 --name=onlyoffice onlyoffice/documentserver`
