### ISSUE TITLE
After docker-compose up HA Proxy not configured

### ISSUE THREAD

**Issue by chrsch** [ONLYOFFICE/Docker-DocumentServer#145] opened 2018-12-12 14:34 UTC
Bug report

**What is the current behavior?**
After "docker-compose up -d" I can see all containers running (docker ps). But on my ip:80 there is no OO Document Server available. I checked haproxy by visiting my ip:1936 and noticed there are no frontends and backends setup.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Get the docker-compose.yml
2. Run docker-compose up -d

**What is the expected behavior?**
After containers are started the document server is available from ip:80

**Did this work in previous versions of DocumentServer?**
Unknown

**DocumentServer Docker tag:**
onlyoffice/documentserver:latest 

**Host Operating System:**
Ubuntu 18 LTS / Docker CE

**Comment by ShockwaveNN** [comment] 2018-12-12 15:52
@chrsch Hi, could you look to logs those services?
I tryied it myself and seems there is a problem with repeating error
`onlyoffice-documentserver_1       | Waiting for connection to the localhost host on port 5432`
Not sure if this is a same problem like yours

**Comment by agolybev** [comment] 2018-12-13 08:10
Hi, I've tested it yesterday. It works for me.

**Comment by ShockwaveNN** [comment] 2018-12-13 16:01
@chrsch Ok, another question.
What is state of logs of `onlyoffice-postgres` container
We can confirm there is some trouble with `ERROR:  relation "checkissupportonconflict" does not exist at character 13` error

**Comment by chrsch** [comment] 2018-12-13 16:07
@ShockwaveNN 
I looked at the postgres container logs, the error is there:

`PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2018-12-12 21:22:04 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
LOG:  incomplete startup packet
ERROR:  relation "checkissupportonconflict" does not exist at character 13
STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
ERROR:  relation "checkissupportonconflict" does not exist at character 13
STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
ERROR:  relation "checkissupportonconflict" does not exist at character 13
STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
ERROR:  relation "checkissupportonconflict" does not exist at character 13
STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
ERROR:  relation "checkissupportonconflict" does not exist at character 13
STATEMENT:  INSERT INTO checkIsSupportOnConflict (id) VALUES(1) ON CONFLICT DO NOTHING;
LOG:  database system was interrupted; last known up at 2018-12-12 21:22:06 UTC
LOG:  incomplete startup packet
FATAL:  the database system is starting up
FATAL:  the database system is starting up
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  redo starts at 0/17039C0
LOG:  invalid record length at 0/172C438
LOG:  redo done at 0/172C410
LOG:  last completed transaction was at log time 2018-12-12 21:22:08.012204+00
LOG:  incomplete startup packet
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  database system was shut down at 2018-12-12 21:45:45 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
LOG:  incomplete startup packet`

**Comment by ShockwaveNN** [comment] 2018-12-13 16:12
@chrsch Ok, so we can confirm this issue, we got some troubles. We're trying to understand what happening

**Comment by ShockwaveNN** [comment] 2018-12-14 13:55
@chrsch could you try to reinit compose several times - seems this problem not related with `relation "checkissupportonconflict" does not exist at character 13`
I was able to reproduce your issue once, but since when - everything is fine. Seems issue have something with starting orders and timeouts of startup process

**Comment by chrsch** [comment] 2018-12-14 20:13
@ShockwaveNN  I'll give it a try and report back. I managed to get it running on Docker @ Mac Mojave and Docker @ Ubuntu 16 LTS. So this seems to be related to Ubuntu 18 LTS in some way. Maybe this info helps figuring out what's going on.

**Comment by hypervtechnics** [comment] 2019-12-10 19:50
has this been solved? i am having this issue too.

**Comment by igwyd** [comment] 2024-11-01 11:16
HAproxy is no longer used in our docker-compose.yml, we will close it

**Closed** 2024-11-02 11:42 UTC
Labels: confirmed-bug
