### ISSUE TITLE
ONLYOFFICE can't download file

### ISSUE THREAD

**Issue by marcellopato** [ONLYOFFICE/Docker-DocumentServer#497] opened 2022-09-16 18:43 UTC
**Do you want to request a *feature* or report a *bug*?**
Can't download a file at any circumstances.

**What is the current behavior?**
The docker container runs ok, can upload a file, but can't edit. The error **Download failed** dialog always shows up.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I don't think it is a bug. It is a misconfiguration that I can't figure.

**What is the expected behavior?**
I expect the file to open in the Editor.

**Did this work in previous versions of DocumentServer?**
Never used DocumentServer before.

**DocumentServer Docker tag:**
```sudo docker run -i -t -d -p 8080:80 onlyoffice/documentserver``` and then, ```sudo docker exec 4c26555e4611 sudo supervisorctl start ds:example``` to start the Example server

**Host Operating System:**
macOS High Sierra
Docker version 20.10.8, build 3967b7d
PHP@7.2
Laravel Valet 3.1.11

Thanks in advance!

**Comment by ShockwaveNN** [comment] 2022-09-16 18:49
I think the problem is that you've accessing DocumentServer via `localhost` or `127.0.0.1` - this wouldn't work

You should use local IP, like `192.168.1.111` or external ip

**Comment by marcellopato** [comment] 2022-09-16 19:01
Perfect. Works like a breeze. Now I need to solve the same issue when running through API. Now I am sure that this is the problem after all. Thanks, @ShockwaveNN !

**Comment by marcellopato** [comment] 2022-09-16 19:02
Better leave it open for a while...

**Comment by ShockwaveNN** [comment] 2022-10-21 19:08
Closing this issue since no feedback for more than a month

**Closed by ShockwaveNN** 2022-10-21 19:08 UTC
