### ISSUE TITLE
Since upgrade to 7.2: "Can't download document"

### ISSUE THREAD

**Issue by vasyugan** [ONLYOFFICE/Docker-DocumentServer#504] opened 2022-09-26 10:16 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Since upgrading the server to 7.2, I get the dreaded "Download failed" message. 

This is what I see when trying to update the settings in Nextcloud:

 `(Client error: GET https://******/cache/files/data/conv_check_2132774431_docx/output.docx/check_********.docx?md5=*****************&expires=****************&filename=check_*********.docx resulted in a 403 Forbidden * response:`

I have run docker container logs -f onlyoffice to see what is happening on the document server side, but nothing appears in the logs at the moment the failure occurs.

Downgrading the docker image to 7.1 lets it work again.
 **DocumentServer Docker tag:**

latest

**Host Operating System:**

Ubuntu 20.04

**Comment by Magneticdud** [comment] 2022-09-26 11:27
Same here, I was thinking I did some mistake with the setup, instead looks like not, because with tag 7.1 works fine

**Comment by ShockwaveNN** [comment] 2022-09-26 13:54
Do you configured (or disabled) JWT correctly?

Because since v7.2 JWT with random key enabled by default for more secure setup

Read more details about this in `http://docserverurl/welcome`

**Comment by vasyugan** [comment] 2022-09-26 13:59
> Do you configured (or disabled) JWT correctly?
> 
> Because since v7.2 JWT with random key enabled by default for more secure setup
> 
> Read more details about this in `http://docserverurl/welcome`

Thanks. I have been using my own secret specified in a custom local.json, which is included as a docker mount. So this secret is no longer being used, apparently.

**Comment by Magneticdud** [comment] 2022-09-26 14:03
For 7.2 I am using a key specified in the `docker-config.yml` file

If i browse the container with `docker exec`, the content of `/etc/onlyoffice/documentserver/local.json` has my jwt key

**Comment by vasyugan** [comment] 2022-09-26 14:07
> Do you configured (or disabled) JWT correctly?
> 
> Because since v7.2 JWT with random key enabled by default for more secure setup
 
yes, the secret is configured correctly. I had it enabled long ago, I also set the JWT header, but since the upgrade to 7.1, it doesn't work anymore. I checked with command at the  URL you provided.

**Comment by ShockwaveNN** [comment] 2022-09-26 14:37
You should not mount local.json for JWT kets, it will cause problems for 100%

For other cases I think we need a way to reproduce, maybe sample simplified docker-compose

**Comment by ShockwaveNN** [comment] 2022-09-26 14:41
It's not deprecated but may be some bug, so need some scenarios

**Comment by ShockwaveNN** [comment] 2022-10-09 17:14
Closing this issue, since problem seems be resolved

**Closed by ShockwaveNN** 2022-10-09 17:14 UTC
