### ISSUE TITLE
Handle wss in X-Forwarded-Proto

### ISSUE THREAD

**Issue by jcgruenhage** [ONLYOFFICE/Docker-DocumentServer#254] opened 2020-05-29 15:33 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Trying to open a document using the document server when using traefik as a reverse proxy fails, because the `X-Forwarded-Proto` header is set to `wss`, which the DocumentServer does not handle correctly. As a workaround, overriding the header in traefik works, but that's annoying and lots of people run into this, ending up quite confused (source: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/151)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 - setup traefik
 - setup nextcloud
 - setup document server
 - open document
![image](https://user-images.githubusercontent.com/6861958/83277379-415c6600-a1d2-11ea-9d3c-adaf7b7f2b63.png)

**What is the expected behavior?**
Being able to open the document for editing.

**Did this work in previous versions of DocumentServer?**
Not sure, probably not.

**DocumentServer Docker tag:**
5.5

**Host Operating System:**
VoidLinux (why does this matter?)

**Comment by SuperSandro2000** [comment] 2020-05-29 16:30
The Traefik example is for Traefik 1.0. This issue only occurs with Traefik 2.0.

**Comment by jcgruenhage** [comment] 2020-05-29 16:41
Even if you update the sample config to work with traefik 2.0, this is not something that should require any special config. Requiring http(s) as X-Forwarded-Proto when the actual protocol is ws(s) is a bug, overriding traefiks behaviour is a workaround that hides the bug, not a fix or a solution.

**Comment by zilexa** [comment] 2021-01-09 23:38
Is there an update or workaround available to get this working with Traefikv2.0?

**Comment by deefdragon** [comment] 2021-08-08 04:57
I also am encountering this, and the solutions posted have not solved it for me. I have confirmed the headers via curl, and disabled cache via chrome-tools. No dice.

**Comment by stavros-k** [comment] 2021-10-02 09:13
Any updates on this? While the workaround might work, I don't like it as a permanent solution.

**Comment by igwyd** [comment] 2024-11-12 07:13
Hello, sorry for the late reply, 
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2162

**Closed** 2024-11-12 08:08 UTC
Labels: duplicate
